import type { Team } from '@/types';

function ratingFromRank(rank: number): number {
  if (rank === 1) return 95;
  if (rank === 2) return 93;
  if (rank === 3) return 92;
  if (rank === 4) return 91;
  if (rank === 5) return 90;
  if (rank === 6) return 89;
  return Math.max(58, 95 - Math.floor(rank * 0.8));
}

export const TEAMS_AF: Omit<Team, 'players'>[] = [
  // ─── Group A ───────────────────────────────────────────
  {
    id: 'MEX',
    name: 'Mexico',
    flag: '🇲🇽',
    rating: ratingFromRank(15),
    rank: 15,
    group: 'A',
    coach: 'Javier Aguirre',
    mascot: 'El Tri',
    style: 'Technical short-passing with passionate tempo and set-piece threat',
    founded: 1927,
    titles: 0,
    finals: 0,
    semifinals: 0,
    bestResult: 'Quarterfinals (1970, 1986)',
    facts: [
      'Co-hosting the 2026 World Cup alongside USA and Canada',
      'Estadio Azteca is the only stadium to host two World Cup finals (1970, 1986)',
      'Eliminated in the Round of 16 at seven consecutive World Cups (1994–2018)',
      'Have qualified for 18 World Cups — more than any nation outside Europe and South America',
    ],
  },
  {
    id: 'KOR',
    name: 'South Korea',
    flag: '🇰🇷',
    rating: ratingFromRank(25),
    rank: 25,
    group: 'A',
    coach: 'Hong Myung-bo',
    mascot: 'Taeguk Warriors',
    style: 'Relentless pressing with explosive pace on the break',
    founded: 1933,
    titles: 0,
    finals: 0,
    semifinals: 1,
    bestResult: 'Fourth place (2002)',
    facts: [
      'Reached the 2002 World Cup semifinals as co-hosts — beating Italy and Spain en route',
      'Son Heung-min is Asia\'s most decorated player in top European leagues',
      'Hong Myung-bo, the current coach, captained the legendary 2002 squad',
      'First Asian team to reach the World Cup semifinals',
    ],
  },
  {
    id: 'RSA',
    name: 'South Africa',
    flag: '🇿🇦',
    rating: ratingFromRank(60),
    rank: 60,
    group: 'A',
    coach: 'Hugo Broos',
    mascot: 'Bafana Bafana',
    style: 'Athletic and direct with pace on the wings',
    founded: 1991,
    titles: 0,
    finals: 0,
    semifinals: 0,
    bestResult: 'Group stage (1998, 2002, 2010)',
    facts: [
      'Hosted the 2010 World Cup — the first and only edition on African soil',
      'Siphiwe Tshabalala scored the opening goal of the 2010 tournament against Mexico',
      'Have never advanced beyond the group stage in three World Cup appearances',
      'Won the 1996 Africa Cup of Nations as hosts — their only continental title',
    ],
  },
  {
    id: 'CZE',
    name: 'Czechia',
    flag: '🇨🇿',
    rating: ratingFromRank(41),
    rank: 41,
    group: 'A',
    coach: 'Ivan Hašek',
    mascot: 'Fotbaloví Reprezentanti',
    style: 'Tactical discipline with technical midfield control',
    founded: 1901,
    titles: 0,
    finals: 2,
    semifinals: 3,
    bestResult: 'Runners-up (1934, 1962 as Czechoslovakia)',
    facts: [
      'Czechoslovakia finished runners-up at the 1934 and 1962 World Cups',
      'Euro 1976 champions as Czechoslovakia — the only major trophy in their history',
      'Petr Čech is the most capped player in Czech national team history',
      'Have not appeared at a World Cup since 2006 as the Czech Republic',
    ],
  },

  // ─── Group B ───────────────────────────────────────────
  {
    id: 'SUI',
    name: 'Switzerland',
    flag: '🇨🇭',
    rating: ratingFromRank(19),
    rank: 19,
    group: 'B',
    coach: 'Murat Yakin',
    mascot: 'Nati',
    style: 'Organized defensive block with sharp counter-attacks',
    founded: 1895,
    titles: 0,
    finals: 0,
    semifinals: 1,
    bestResult: 'Quarterfinals (1934, 1938, 1954)',
    facts: [
      'Finished fourth at the 1954 World Cup — their best-ever finish',
      'UEFA headquarters are in Nyon, Switzerland',
      'Have appeared at 13 World Cups without ever reaching a final',
      'Eliminated holders Italy from Euro 2024 in a dominant round-of-16 performance',
    ],
  },
  {
    id: 'CAN',
    name: 'Canada',
    flag: '🇨🇦',
    rating: ratingFromRank(30),
    rank: 30,
    group: 'B',
    coach: 'Jesse Marsch',
    mascot: 'Les Rouges',
    style: 'High-energy pressing with emerging young talent',
    founded: 1912,
    titles: 0,
    finals: 0,
    semifinals: 0,
    bestResult: 'Group stage (1986, 2022)',
    facts: [
      'Co-hosting the 2026 World Cup — their first home matches since 1986',
      'Qualified for back-to-back World Cups in 2022 and 2026 after a 36-year absence',
      'Alphonso Davies is one of the fastest full-backs in world football',
      'Lost all three group matches in their 1986 debut without scoring a goal',
    ],
  },
  {
    id: 'QAT',
    name: 'Qatar',
    flag: '🇶🇦',
    rating: ratingFromRank(35),
    rank: 35,
    group: 'B',
    coach: 'Félix Sánchez',
    mascot: 'Al-Annabi',
    style: 'Technical possession with disciplined defensive shape',
    founded: 1960,
    titles: 0,
    finals: 0,
    semifinals: 0,
    bestResult: 'Group stage (2022)',
    facts: [
      'Hosted the 2022 World Cup — the first Arab nation and smallest country to do so',
      'Won the 2019 AFC Asian Cup, their greatest football achievement',
      'Spent over $200 billion preparing infrastructure for the 2022 tournament',
      'Lost all three group matches in their 2022 World Cup debut',
    ],
  },
  {
    id: 'BIH',
    name: 'Bosnia & Herzegovina',
    flag: '🇧🇦',
    rating: ratingFromRank(52),
    rank: 52,
    group: 'B',
    coach: 'Sergej Barbarez',
    mascot: 'Zmajevi',
    style: 'Technical midfield play with physical presence up front',
    founded: 1992,
    titles: 0,
    finals: 0,
    semifinals: 0,
    bestResult: 'Group stage (2014)',
    facts: [
      'Made their only World Cup appearance in 2014 in Brazil',
      'Edin Džeko is the country\'s all-time top scorer with over 60 international goals',
      'Sergej Barbarez, the current coach, is a former national team legend and top scorer',
      'Narrowly missed out on the 2018 World Cup after losing a playoff to Republic of Ireland',
    ],
  },

  // ─── Group C ───────────────────────────────────────────
  {
    id: 'BRA',
    name: 'Brazil',
    flag: '🇧🇷',
    rating: ratingFromRank(6),
    rank: 6,
    group: 'C',
    coach: 'Dorival Jr',
    mascot: 'Canarinho',
    style: 'Joga Bonito — flair, pressing, and quick transitions',
    founded: 1914,
    titles: 5,
    finals: 7,
    semifinals: 11,
    bestResult: 'Champions (1958, 1962, 1970, 1994, 2002)',
    facts: [
      'Only nation to appear in every World Cup edition (22 tournaments)',
      'Pelé is the only player to win three World Cups (1958, 1962, 1970)',
      'Their 7-1 loss to Germany in the 2014 semifinal is called the Mineirazo',
      'Hold the record for most World Cup goals scored with over 230',
    ],
  },
  {
    id: 'MAR',
    name: 'Morocco',
    flag: '🇲🇦',
    rating: ratingFromRank(8),
    rank: 8,
    group: 'C',
    coach: 'Walid Regragui',
    mascot: 'Atlas Lions',
    style: 'Fearless defensive wall with lethal set-pieces and rapid counters',
    founded: 1955,
    titles: 0,
    finals: 0,
    semifinals: 1,
    bestResult: 'Fourth place (2022)',
    facts: [
      'First African and Arab nation to reach a World Cup semifinal in 2022',
      'Conceded just one goal — an own goal — across five knockout matches in 2022',
      'Beat Belgium, Spain, and Portugal on their run to the 2022 semifinals',
      'Youssef En-Nesyri\'s header against Portugal is one of African football\'s iconic goals',
    ],
  },
  {
    id: 'SCO',
    name: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    rating: ratingFromRank(47),
    rank: 47,
    group: 'C',
    coach: 'Steve Clarke',
    mascot: 'Tartan Army',
    style: 'Organized and combative with set-piece threat',
    founded: 1873,
    titles: 0,
    finals: 0,
    semifinals: 0,
    bestResult: 'Group stage (1954, 1958, 1974, 1978, 1982, 1986, 1990, 1998)',
    facts: [
      'Have never advanced past the group stage in eight World Cup appearances',
      'One of the oldest national teams in the world, playing their first match in 1872',
      'Qualified for Euro 2020 — their first major tournament since 1998',
      'Archie Gemmill\'s solo goal against Netherlands in 1978 is a World Cup classic',
    ],
  },
  {
    id: 'HAI',
    name: 'Haiti',
    flag: '🇭🇹',
    rating: ratingFromRank(83),
    rank: 83,
    group: 'C',
    coach: 'Marc Collat',
    mascot: 'Les Grenadiers',
    style: 'Physical and direct with passionate attacking flair',
    founded: 1904,
    titles: 0,
    finals: 0,
    semifinals: 0,
    bestResult: 'Group stage (1974)',
    facts: [
      'First Caribbean nation to qualify for the World Cup in 1974',
      'Manno Sanon scored Haiti\'s first-ever World Cup goal against Italy in 1974',
      'Have made only one World Cup appearance in their history',
      'Won the 1973 CONCACAF Championship to earn their 1974 World Cup berth',
    ],
  },

  // ─── Group D ───────────────────────────────────────────
  {
    id: 'USA',
    name: 'United States',
    flag: '🇺🇸',
    rating: ratingFromRank(16),
    rank: 16,
    group: 'D',
    coach: 'Mauricio Pochettino',
    mascot: 'The Yanks',
    style: 'High-energy pressing with athletic, fearless talent',
    founded: 1913,
    titles: 0,
    finals: 0,
    semifinals: 1,
    bestResult: 'Third place (1930)',
    facts: [
      'Co-hosting the 2026 World Cup — the biggest sporting event in US history',
      'Beat England 1-0 in the 1950 World Cup — one of football\'s greatest upsets',
      'Finished third at the inaugural 1930 World Cup in Uruguay',
      'Landon Donovan is the USMNT\'s all-time leading scorer with 57 goals',
    ],
  },
  {
    id: 'AUS',
    name: 'Australia',
    flag: '🇦🇺',
    rating: ratingFromRank(26),
    rank: 26,
    group: 'D',
    coach: 'Tony Popovic',
    mascot: 'Socceroos',
    style: 'Hard-working defensive structure with aerial threat and direct play',
    founded: 1961,
    titles: 0,
    finals: 0,
    semifinals: 0,
    bestResult: 'Round of 16 (2006, 2022)',
    facts: [
      'Beat Denmark 1-0 to reach the Round of 16 at the 2022 World Cup',
      'Changed confederation from OFC to AFC in 2006 for stronger competition',
      'Tim Cahill scored in three consecutive World Cups (2006, 2010, 2014)',
      'Qualified for six consecutive World Cups from 2006 to 2022',
    ],
  },
  {
    id: 'PAR',
    name: 'Paraguay',
    flag: '🇵🇾',
    rating: ratingFromRank(64),
    rank: 64,
    group: 'D',
    coach: 'Alfaro',
    mascot: 'Albirroja',
    style: 'Physical defensive football with quick counter-attacks',
    founded: 1906,
    titles: 0,
    finals: 0,
    semifinals: 0,
    bestResult: 'Quarterfinals (2010)',
    facts: [
      'Reached the quarterfinals in 2010 — their best-ever World Cup run',
      'Reached the Round of 16 in four consecutive World Cups (1986, 1998, 2002, 2010)',
      'José Luis Chilavert scored a hat-trick for Vélez Sarsfield in 1999 — a rare feat for a goalkeeper',
      'Reached the knockout rounds in five consecutive World Cups from 1986 to 2010',
    ],
  },
  {
    id: 'TUR',
    name: 'Türkiye',
    flag: '🇹🇷',
    rating: ratingFromRank(42),
    rank: 42,
    group: 'D',
    coach: 'Vincenzo Montella',
    mascot: 'Ay-Yıldızlılar',
    style: 'Organized defensive structure with rapid transitions and set-piece power',
    founded: 1923,
    titles: 0,
    finals: 0,
    semifinals: 1,
    bestResult: 'Third place (2002)',
    facts: [
      'Finished third at the 2002 World Cup — their greatest football achievement',
      'Beat Brazil 2-1 in the 2002 group stage on their run to the semifinals',
      'Hakan Şükür scored the fastest goal in World Cup history (11 seconds) in 2002',
      'Reached the Euro 2008 semifinals — another landmark for Turkish football',
    ],
  },

  // ─── Group E ───────────────────────────────────────────
  {
    id: 'GER',
    name: 'Germany',
    flag: '🇩🇪',
    rating: ratingFromRank(10),
    rank: 10,
    group: 'E',
    coach: 'Julian Nagelsmann',
    mascot: 'Die Mannschaft',
    style: 'Gegenpressing with technical midfield control',
    founded: 1900,
    titles: 4,
    finals: 8,
    semifinals: 13,
    bestResult: 'Champions (1954, 1974, 1990, 2014)',
    facts: [
      'Only nation to win the World Cup in three different decades',
      'Miroslav Klose holds the all-time World Cup goal record with 16 goals',
      'The 7-1 victory over Brazil in the 2014 semifinal is the largest margin in a World Cup semifinal',
      'Were eliminated in the group stage in 2018 and 2022 — unprecedented for Germany',
    ],
  },
  {
    id: 'CIV',
    name: 'Ivory Coast',
    flag: '🇨🇮',
    rating: ratingFromRank(33),
    rank: 33,
    group: 'E',
    coach: 'Emerse Faé',
    mascot: 'Les Éléphants',
    style: 'Powerful and athletic with explosive attacking talent',
    founded: 1960,
    titles: 0,
    finals: 0,
    semifinals: 0,
    bestResult: 'Group stage (2006, 2010, 2014)',
    facts: [
      'Won the 2023 Africa Cup of Nations on home soil under coach Emerse Faé',
      'Didier Drogba is the country\'s all-time top scorer with 65 international goals',
      'Have appeared at three World Cups but never reached the knockout rounds',
      'Were drawn into the "Group of Death" with Brazil, Portugal, and North Korea in 2010',
    ],
  },
  {
    id: 'ECU',
    name: 'Ecuador',
    flag: '🇪🇨',
    rating: ratingFromRank(24),
    rank: 24,
    group: 'E',
    coach: 'Sebastián Beccacece',
    mascot: 'La Tri',
    style: 'Altitude-hardened fitness with direct, physical attacking play',
    founded: 1925,
    titles: 0,
    finals: 0,
    semifinals: 0,
    bestResult: 'Round of 16 (2006)',
    facts: [
      'Home matches in Quito at 2,850m altitude provide a significant advantage',
      'Enner Valencia is Ecuador\'s all-time top scorer and scored in multiple World Cups',
      'Have qualified for four World Cups (2002, 2006, 2014, 2022)',
      'Reached the Round of 16 in 2006 before losing to England',
    ],
  },
  {
    id: 'CUW',
    name: 'Curaçao',
    flag: '🇨🇼',
    rating: ratingFromRank(81),
    rank: 81,
    group: 'E',
    coach: 'Dick Advocaat',
    mascot: 'Trupiañanan',
    style: 'Disciplined defensive organization with quick wide transitions',
    founded: 2011,
    titles: 0,
    finals: 0,
    semifinals: 0,
    bestResult: 'Debut tournament',
    facts: [
      'Gained independent FIFA membership in 2011 after splitting from the Netherlands Antilles',
      'Dick Advocaat has managed at four World Cups with the Netherlands, South Korea, Russia, and Ecuador',
      'Leandro Bacuna and Cuco Martina are among the island\'s most capped internationals',
      'One of the smallest nations by population ever to qualify for a World Cup',
    ],
  },

  // ─── Group F ───────────────────────────────────────────
  {
    id: 'NED',
    name: 'Netherlands',
    flag: '🇳🇱',
    rating: ratingFromRank(7),
    rank: 7,
    group: 'F',
    coach: 'Ronald Koeman',
    mascot: 'Oranje',
    style: 'Total Football — fluid positioning and relentless pressing',
    founded: 1889,
    titles: 0,
    finals: 3,
    semifinals: 5,
    bestResult: 'Runners-up (1974, 1978, 2010)',
    facts: [
      'Invented Total Football under Rinus Michels and Johan Cruyff in the 1970s',
      'Have reached three World Cup finals without ever winning the trophy',
      'Finished third at the 2014 World Cup with a stunning 5-1 win over Spain',
      'Johan Cruyff refused to play the 1978 final due to political reasons in Argentina',
    ],
  },
  {
    id: 'JPN',
    name: 'Japan',
    flag: '🇯🇵',
    rating: ratingFromRank(18),
    rank: 18,
    group: 'F',
    coach: 'Hajime Moriyasu',
    mascot: 'Samurai Blue',
    style: 'Disciplined pressing with rapid combination play',
    founded: 1921,
    titles: 0,
    finals: 0,
    semifinals: 0,
    bestResult: 'Round of 16 (2002, 2010, 2018, 2022)',
    facts: [
      'Beat both Germany and Spain in the 2022 World Cup group stage',
      'Fans clean the stadium after every match — a beloved global tradition',
      'Have reached the Round of 16 four times but never the quarterfinals',
      'Co-hosted the 2002 World Cup with South Korea',
    ],
  },
  {
    id: 'SWE',
    name: 'Sweden',
    flag: '🇸🇪',
    rating: ratingFromRank(39),
    rank: 39,
    group: 'F',
    coach: 'Jon Dahl Tomasson',
    mascot: 'Blågult',
    style: 'Direct, physical football with strong set-piece and aerial threat',
    founded: 1904,
    titles: 0,
    finals: 1,
    semifinals: 4,
    bestResult: 'Runners-up (1958)',
    facts: [
      'Finished runners-up on home soil in 1958, losing the final 5-2 to Brazil',
      'Zlatan Ibrahimović never played in a World Cup despite 122 caps for Sweden',
      'Finished third at the 1950 and 1994 World Cups',
      'Henrik Larsson and Freddie Ljungberg led a golden generation in the early 2000s',
    ],
  },
  {
    id: 'TUN',
    name: 'Tunisia',
    flag: '🇹🇳',
    rating: ratingFromRank(40),
    rank: 40,
    group: 'F',
    coach: 'Faouzi Benzarti',
    mascot: 'Les Aigles de Carthage',
    style: 'Compact defensive structure with tactical discipline',
    founded: 1957,
    titles: 0,
    finals: 0,
    semifinals: 0,
    bestResult: 'Group stage (1978, 1998, 2002, 2006, 2018, 2022)',
    facts: [
      'First African nation to win a World Cup match — beating Mexico 3-1 in 1978',
      'Beat holders France 1-0 in the 2022 World Cup group stage',
      'Have appeared at six World Cups but never reached the knockout rounds',
      'Won the 2004 Africa Cup of Nations on home soil',
    ],
  },
];
