import type { SquadList } from '@/types';

export const SQUADS_REST: Record<string, SquadList> = {
  MEX: {
    gk: [
      { id: 'ochoa', name: 'Guillermo Ochoa', number: 1, club: 'Salernitana', age: 39 },
      { id: 'malagon', name: 'Luis Malagón', number: 13, club: 'América', age: 28 },
      { id: 'rangel', name: 'Raúl Rangel', number: 23, club: 'León', age: 27 },
    ],
    def: [
      { id: 'arteaga', name: 'Gerardo Arteaga', number: 19, club: 'Monterrey', age: 27 },
      { id: 'gallardo', name: 'Jesús Gallardo', number: 4, club: 'Monterrey', age: 30 },
      { id: 'montes', name: 'César Montes', number: 3, club: 'Almería', age: 28 },
      { id: 'vasquez', name: 'Johan Vásquez', number: 5, club: 'Genoa', age: 27 },
      { id: 'sanchez', name: 'Jorge Sánchez', number: 2, club: 'Columbus Crew', age: 28 },
      { id: 'reyes', name: 'Israel Reyes', number: 21, club: 'América', age: 25 },
      { id: 'cuesta', name: 'Carlos Cuesta', number: 15, club: 'Atlético Nacional', age: 26 },
      { id: 'campos', name: 'Omar Campos', number: 26, club: 'LA Galaxy', age: 24 },
    ],
    mid: [
      { id: 'alvarez', name: 'Edson Álvarez', number: 14, club: 'West Ham', age: 28 },
      { id: 'herrera', name: 'Héctor Herrera', number: 16, club: 'Houston Dynamo', age: 35 },
      { id: 'chavez', name: 'Luis Chávez', number: 8, club: 'Dynamo Moscow', age: 29 },
      { id: 'pineda', name: 'Orbelín Pineda', number: 17, club: 'AEK Athens', age: 29 },
      { id: 'rodriguez', name: 'Carlos Rodríguez', number: 18, club: 'Cruz Azul', age: 28 },
      { id: 'guardado', name: 'Andrés Guardado', number: 10, club: 'León', age: 38 },
      { id: 'quinones', name: 'Luis Quiñones', number: 11, club: 'Tigres', age: 28 },
      { id: 'gutierrez', name: 'Erick Gutiérrez', number: 6, club: 'PSV', age: 30 },
    ],
    fwd: [
      { id: 'lozano', name: 'Hirving Lozano', number: 9, club: 'PSV', age: 30 },
      { id: 'gimenez', name: 'Santiago Giménez', number: 12, club: 'Feyenoord', age: 24 },
      { id: 'vega', name: 'Alexis Vega', number: 7, club: 'Toluca', age: 28 },
      { id: 'antuna', name: 'Uriel Antuna', number: 20, club: 'América', age: 27 },
      { id: 'quinones-j', name: 'Julián Quiñones', number: 24, club: 'América', age: 28 },
      { id: 'martin', name: 'Henry Martín', number: 22, club: 'América', age: 33 },
      { id: 'jimenez', name: 'Raúl Jiménez', number: 25, club: 'Fulham', age: 34 },
    ],
  },
  KOR: {
    gk: [
      { id: 'joho', name: 'Jo Hyeon-woo', number: 21, club: 'Ulsan HD', age: 34 },
      { id: 'song', name: 'Song Bum-keun', number: 1, club: 'Jeonbuk Motors', age: 28 },
      { id: 'kim-seunggyu', name: 'Kim Seung-gyu', number: 23, club: 'Al-Shabab', age: 34 },
    ],
    def: [
      { id: 'kim-minjae', name: 'Kim Min-jae', number: 4, club: 'Bayern Munich', age: 29 },
      { id: 'kim-youngwon', name: 'Kim Young-gwon', number: 19, club: 'Ulsan HD', age: 35 },
      { id: 'kim-jinsu', name: 'Kim Jin-su', number: 2, club: 'Jeonbuk Motors', age: 33 },
      { id: 'kim-moonhwan', name: 'Kim Moon-hwan', number: 3, club: 'Anderlecht', age: 30 },
      { id: 'jeong-seunghyun', name: 'Jeong Seung-hyun', number: 5, club: 'Ulsan HD', age: 27 },
      { id: 'park-kyuhyun', name: 'Park Kyu-hyun', number: 22, club: 'Suwon Samsung', age: 25 },
      { id: 'cho-yumin', name: 'Cho Yu-min', number: 6, club: 'Daejeon Hana', age: 26 },
      { id: 'hong-hyunseok', name: 'Hong Hyun-seok', number: 20, club: 'Genk', age: 26 },
    ],
    mid: [
      { id: 'lee-kangin', name: 'Lee Kang-in', number: 10, club: 'PSG', age: 24 },
      { id: 'jung-wooyoung', name: 'Jung Woo-young', number: 14, club: 'Stuttgart', age: 26 },
      { id: 'hwang-inbeom', name: 'Hwang In-beom', number: 8, club: 'Feyenoord', age: 28 },
      { id: 'paik-seungho', name: 'Paik Seung-ho', number: 18, club: 'Birmingham City', age: 28 },
      { id: 'jeong-wooyeong', name: 'Jeong Woo-yeong', number: 7, club: 'Stuttgart', age: 26 },
      { id: 'lee-jaesung', name: 'Lee Jae-sung', number: 11, club: 'Mainz', age: 32 },
      { id: 'hwang-uijo', name: 'Hwang Ui-jo', number: 16, club: 'Nottingham Forest', age: 33 },
      { id: 'yang-minhyeok', name: 'Yang Min-hyeok', number: 17, club: 'Tottenham', age: 19 },
    ],
    fwd: [
      { id: 'son', name: 'Son Heung-min', number: 9, club: 'LAFC', age: 34 },
      { id: 'cho-guesung', name: 'Cho Gue-sung', number: 12, club: 'Midtjylland', age: 27 },
      { id: 'hwang-heechan', name: 'Hwang Hee-chan', number: 13, club: 'Wolverhampton', age: 29 },
      { id: 'oh-hyeongyu', name: 'Oh Hyeon-gyu', number: 15, club: 'Genk', age: 24 },
      { id: 'park-eunjoong', name: 'Park Eun-joong', number: 24, club: 'Gwangju FC', age: 22 },
      { id: 'jeong-sangbin', name: 'Jeong Sang-bin', number: 25, club: 'Minnesota United', age: 22 },
      { id: 'lee-seungmo', name: 'Lee Seung-mo', number: 26, club: 'Gwangju FC', age: 27 },
    ],
  },
  RSA: {
    gk: [
      { id: 'williams', name: 'Ronwen Williams', number: 16, club: 'Mamelodi Sundowns', age: 33 },
      { id: 'mothwa', name: 'Veli Mothwa', number: 22, club: 'Mamelodi Sundowns', age: 29 },
      { id: 'goss', name: 'Ricardo Goss', number: 1, club: 'SuperSport United', age: 30 },
    ],
    def: [
      { id: 'mudau', name: 'Khuliso Mudau', number: 2, club: 'Mamelodi Sundowns', age: 28 },
      { id: 'kekana', name: 'Grant Kekana', number: 4, club: 'Mamelodi Sundowns', age: 32 },
      { id: 'mvala', name: 'Mothobi Mvala', number: 3, club: 'Mamelodi Sundowns', age: 30 },
      { id: 'modiba', name: 'Aubrey Modiba', number: 6, club: 'Mamelodi Sundowns', age: 30 },
      { id: 'mashego', name: 'Terrence Mashego', number: 13, club: 'Mamelodi Sundowns', age: 29 },
      { id: 'xulu', name: 'Siyanda Xulu', number: 15, club: 'Kaizer Chiefs', age: 34 },
      { id: 'mokoena', name: 'Teboho Mokoena', number: 5, club: 'Mamelodi Sundowns', age: 28 },
      { id: 'cupido', name: 'Keanu Cupido', number: 14, club: 'Mamelodi Sundowns', age: 28 },
    ],
    mid: [
      { id: 'zwane', name: 'Themba Zwane', number: 8, club: 'Mamelodi Sundowns', age: 35 },
      { id: 'aubaas', name: 'Bathusi Aubaas', number: 7, club: 'Mamelodi Sundowns', age: 28 },
      { id: 'mosele', name: 'Goodman Mosele', number: 10, club: 'Orlando Pirates', age: 25 },
      { id: 'mthethwa', name: 'Sphelele Mthethwa', number: 11, club: 'AmaZulu', age: 28 },
      { id: 'maseko', name: 'Thapelo Maseko', number: 17, club: 'Mamelodi Sundowns', age: 22 },
      { id: 'mateta', name: 'Sphephelo Mateta', number: 18, club: 'Stellenbosch', age: 24 },
      { id: 'monare', name: 'Thabang Monare', number: 19, club: 'Orlando Pirates', age: 30 },
      { id: 'makola', name: 'Mokete Makola', number: 20, club: 'Sekhukhune United', age: 27 },
    ],
    fwd: [
      { id: 'tau', name: 'Percy Tau', number: 9, club: 'Al Ahly', age: 31 },
      { id: 'makgopa', name: 'Evidence Makgopa', number: 12, club: 'Orlando Pirates', age: 25 },
      { id: 'rayners', name: 'Iqraam Rayners', number: 21, club: 'Stellenbosch', age: 29 },
      { id: 'foster', name: 'Lyle Foster', number: 23, club: 'Burnley', age: 25 },
      { id: 'appollis', name: 'Oswin Appollis', number: 24, club: 'Cape Town City', age: 22 },
      { id: 'dolly', name: 'Keagan Dolly', number: 25, club: 'Mamelodi Sundowns', age: 32 },
      { id: 'sirino', name: 'Gastón Sirino', number: 26, club: 'Mamelodi Sundowns', age: 34 },
    ],
  },
  CZE: {
    gk: [
      { id: 'vaclik', name: 'Tomáš Vaclík', number: 23, club: 'Sparta Prague', age: 37 },
      { id: 'kovar', name: 'Matěj Kovář', number: 1, club: 'Bayer Leverkusen', age: 25 },
      { id: 'kolar', name: 'Ondřej Kolář', number: 16, club: 'Slavia Prague', age: 30 },
    ],
    def: [
      { id: 'coufal', name: 'Vladimír Coufal', number: 5, club: 'West Ham', age: 33 },
      { id: 'zima', name: 'David Zima', number: 2, club: 'Slavia Prague', age: 25 },
      { id: 'krejcik', name: 'Jakub Krejčí', number: 18, club: 'Girona', age: 26 },
      { id: 'kudela', name: 'Ondřej Kúdela', number: 4, club: 'Slavia Prague', age: 38 },
      { id: 'vlcek', name: 'Tomáš Vlček', number: 3, club: 'Slavia Prague', age: 25 },
      { id: 'vitik', name: 'Martin Vitík', number: 6, club: 'Sparta Prague', age: 22 },
      { id: 'zmrzly', name: 'Ondřej Zmrzlý', number: 19, club: 'Slavia Prague', age: 26 },
      { id: 'chaloupek', name: 'Filip Chaloupek', number: 22, club: 'Sparta Prague', age: 22 },
    ],
    mid: [
      { id: 'holeso', name: 'Tomáš Holeš', number: 9, club: 'Slavia Prague', age: 32 },
      { id: 'barak', name: 'Antonín Barák', number: 7, club: 'Fiorentina', age: 31 },
      { id: 'soucek', name: 'Tomáš Souček', number: 8, club: 'West Ham', age: 30 },
      { id: 'provod', name: 'Lukáš Provod', number: 11, club: 'Slavia Prague', age: 27 },
      { id: 'sadilek', name: 'Michal Sadílek', number: 12, club: 'Slavia Prague', age: 26 },
      { id: 'masopust', name: 'Lukáš Masopust', number: 13, club: 'Slavia Prague', age: 32 },
      { id: 'sulc', name: 'Pavel Šulc', number: 14, club: 'Bayer Leverkusen', age: 25 },
      { id: 'sevcik', name: 'Petr Ševčík', number: 15, club: 'Slavia Prague', age: 26 },
    ],
    fwd: [
      { id: 'schick', name: 'Patrik Schick', number: 10, club: 'Bayer Leverkusen', age: 30 },
      { id: 'hlozek', name: 'Adam Hložek', number: 20, club: 'Bayer Leverkusen', age: 23 },
      { id: 'haraslin', name: 'Lukáš Haraslín', number: 17, club: 'Sparta Prague', age: 29 },
      { id: 'chory', name: 'Jan Chory', number: 21, club: 'Plzeň', age: 31 },
      { id: 'vydra', name: 'Matěj Vydra', number: 24, club: 'Burnley', age: 33 },
      { id: 'nguyen', name: 'Tomáš Nguyen', number: 25, club: 'Sparta Prague', age: 24 },
      { id: 'jablonsky', name: 'Martin Jablonský', number: 26, club: 'Plzeň', age: 23 },
    ],
  },
  SUI: {
    gk: [
      { id: 'sommer', name: 'Yann Sommer', number: 1, club: 'Inter Milan', age: 37 },
      { id: 'kobel', name: 'Gregor Kobel', number: 21, club: 'Borussia Dortmund', age: 28 },
      { id: 'mvogo', name: 'Yvon Mvogo', number: 12, club: 'Lorient', age: 31 },
    ],
    def: [
      { id: 'akanji', name: 'Manuel Akanji', number: 5, club: 'Borussia Dortmund', age: 30 },
      { id: 'schar', name: 'Fabian Schär', number: 4, club: 'Newcastle', age: 34 },
      { id: 'rodriguez', name: 'Ricardo Rodríguez', number: 13, club: 'Torino', age: 33 },
      { id: 'elvedi', name: 'Nico Elvedi', number: 2, club: 'Borussia Mönchengladbach', age: 29 },
      { id: 'widmer', name: 'Silvan Widmer', number: 3, club: 'Mainz', age: 32 },
      { id: 'zesiger', name: 'Cédric Zesiger', number: 6, club: 'Wolfsburg', age: 27 },
      { id: 'mbabu', name: 'Kevin Mbabu', number: 19, club: 'Marseille', age: 30 },
      { id: 'lotomba', name: 'Jordan Lotomba', number: 22, club: 'Nice', age: 27 },
    ],
    mid: [
      { id: 'xhaka', name: 'Granit Xhaka', number: 10, club: 'Bayer Leverkusen', age: 33 },
      { id: 'freuler', name: 'Remo Freuler', number: 8, club: 'Bologna', age: 33 },
      { id: 'shaqiri', name: 'Xherdan Shaqiri', number: 23, club: 'Chicago Fire', age: 34 },
      { id: 'rieder', name: 'Fabian Rieder', number: 14, club: 'Augsburg', age: 23 },
      { id: 'zakaria', name: 'Denis Zakaria', number: 16, club: 'Monaco', age: 29 },
      { id: 'fassnacht', name: 'Christian Fassnacht', number: 18, club: 'Leeds United', age: 31 },
      { id: 'steffen', name: 'Renato Steffen', number: 15, club: 'Lugano', age: 33 },
      { id: 'aebischer', name: 'Michel Aebischer', number: 17, club: 'Bologna', age: 28 },
    ],
    fwd: [
      { id: 'embolo', name: 'Breel Embolo', number: 7, club: 'Monaco', age: 28 },
      { id: 'vargas', name: 'Ruben Vargas', number: 9, club: 'Augsburg', age: 27 },
      { id: 'ndoye', name: 'Dan Ndoye', number: 11, club: 'Bologna', age: 25 },
      { id: 'duah', name: 'Kwadwo Duah', number: 20, club: 'Lugano', age: 28 },
      { id: 'amdouni', name: 'Zeki Amdouni', number: 24, club: 'Burnley', age: 25 },
      { id: 'kalajdzic', name: 'Sasa Kalajdzic', number: 25, club: 'Wolverhampton', age: 28 },
      { id: 'okafor', name: 'Noah Okafor', number: 26, club: 'AC Milan', age: 25 },
    ],
  },
  CAN: {
    gk: [
      { id: 'borjan', name: 'Milan Borjan', number: 1, club: 'Red Star Belgrade', age: 38 },
      { id: 'crepeau', name: 'Maxime Crépeau', number: 16, club: 'Portland Timbers', age: 31 },
      { id: 'stclair', name: 'Dayne St. Clair', number: 23, club: 'Minnesota United', age: 28 },
    ],
    def: [
      { id: 'davies', name: 'Alphonso Davies', number: 2, club: 'Bayern Munich', age: 25 },
      { id: 'johnston', name: 'Alistair Johnston', number: 3, club: 'Celtic', age: 27 },
      { id: 'vitoria', name: 'Steven Vitoria', number: 4, club: 'Gil Vicente', age: 38 },
      { id: 'cornelius', name: 'Derek Cornelius', number: 5, club: 'Malmö', age: 27 },
      { id: 'miller', name: 'Kamal Miller', number: 6, club: 'Portland Timbers', age: 28 },
      { id: 'laryea', name: 'Richie Laryea', number: 13, club: 'Toronto FC', age: 30 },
      { id: 'adekugbe', name: 'Sam Adekugbe', number: 14, club: 'Hatayspor', age: 30 },
      { id: 'bassong', name: 'Zorhan Bassong', number: 22, club: 'Nashville SC', age: 25 },
    ],
    mid: [
      { id: 'eustaquio', name: 'Stephen Eustáquio', number: 7, club: 'Porto', age: 28 },
      { id: 'buchanan', name: 'Tajon Buchanan', number: 8, club: 'Inter Milan', age: 26 },
      { id: 'david', name: 'Jonathan David', number: 10, club: 'Lille', age: 26 },
      { id: 'kone', name: 'Ismaël Koné', number: 11, club: 'Watford', age: 22 },
      { id: 'millar', name: 'Liam Millar', number: 15, club: 'Preston', age: 26 },
      { id: 'piette', name: 'Sam Piette', number: 17, club: 'CF Montréal', age: 31 },
      { id: 'kaye', name: 'Mark-Anthony Kaye', number: 18, club: 'LAFC', age: 30 },
      { id: 'okello', name: 'Noble Okello', number: 19, club: 'Helsingborg', age: 25 },
    ],
    fwd: [
      { id: 'larin', name: 'Cyle Larin', number: 9, club: 'Mallorca', age: 30 },
      { id: 'hoilett', name: 'Junior Hoilett', number: 12, club: 'Reading', age: 33 },
      { id: 'shaffelburg', name: 'Jacob Shaffelburg', number: 20, club: 'Nashville SC', age: 24 },
      { id: 'bair', name: 'Theo Bair', number: 21, club: 'Vancouver Whitecaps', age: 26 },
      { id: 'cavallini', name: 'Lucas Cavallini', number: 24, club: 'Vancouver Whitecaps', age: 33 },
      { id: 'ricketts', name: 'Tosaint Ricketts', number: 25, club: 'Vancouver FC', age: 37 },
      { id: 'nelson', name: 'Jayden Nelson', number: 26, club: 'Norwich City', age: 22 },
    ],
  },
  QAT: {
    gk: [
      { id: 'alsheeb', name: 'Saad Al-Sheeb', number: 1, club: 'Al-Sadd', age: 35 },
      { id: 'barsham', name: 'Meshaal Barsham', number: 22, club: 'Al-Sadd', age: 28 },
      { id: 'hassan-gk', name: 'Yousef Hassan', number: 23, club: 'Al-Gharafa', age: 27 },
    ],
    def: [
      { id: 'miguel', name: 'Pedro Miguel', number: 2, club: 'Al-Sadd', age: 34 },
      { id: 'abdelkarim', name: 'Abdelkarim Hassan', number: 3, club: 'Al-Sadd', age: 31 },
      { id: 'rawi', name: 'Bassam Al-Rawi', number: 4, club: 'Al-Duhail', age: 28 },
      { id: 'salman', name: 'Tarek Salman', number: 5, club: 'Al-Sadd', age: 28 },
      { id: 'khoder', name: 'Musab Khoder', number: 13, club: 'Al-Arabi', age: 26 },
      { id: 'roro', name: 'Ró-Ró', number: 14, club: 'Al-Sadd', age: 34 },
      { id: 'khoukhi', name: 'Boualem Khoukhi', number: 16, club: 'Al-Sadd', age: 35 },
      { id: 'fadlalla', name: 'Ahmed Fadlalla', number: 18, club: 'Al-Rayyan', age: 28 },
    ],
    mid: [
      { id: 'afif', name: 'Akram Afif', number: 11, club: 'Al-Sadd', age: 29 },
      { id: 'hatem', name: 'Abdulaziz Hatem', number: 6, club: 'Al-Rayyan', age: 34 },
      { id: 'boudiaf', name: 'Karim Boudiaf', number: 12, club: 'Al-Duhail', age: 34 },
      { id: 'haydos', name: 'Hassan Al-Haydos', number: 10, club: 'Al-Sadd', age: 34 },
      { id: 'alaaeldin', name: 'Ahmed Alaaeldin', number: 7, club: 'Al-Gharafa', age: 33 },
      { id: 'meshaal', name: 'Mostafa Meshaal', number: 8, club: 'Al-Wakrah', age: 25 },
      { id: 'aymen', name: 'Youssef Aymen', number: 15, club: 'Al-Arabi', age: 24 },
      { id: 'asad', name: 'Ali Asad', number: 17, club: 'Al-Sadd', age: 26 },
    ],
    fwd: [
      { id: 'almoez', name: 'Almoez Ali', number: 9, club: 'Al-Duhail', age: 29 },
      { id: 'muntari', name: 'Mohammed Muntari', number: 20, club: 'Al-Duhail', age: 32 },
      { id: 'ghayeb', name: 'Ayemen Ghayeb', number: 21, club: 'Al-Arabi', age: 23 },
      { id: 'shafi', name: 'Mubarak Shafi', number: 24, club: 'Al-Wakrah', age: 25 },
      { id: 'abdurisaq', name: 'Yousuf Abdurisag', number: 25, club: 'Al-Arabi', age: 22 },
      { id: 'amir', name: 'Amir Hassan', number: 26, club: 'Al-Sailiya', age: 24 },
      { id: 'guevara', name: 'Guevara', number: 19, club: 'Al-Sadd', age: 27 },
    ],
  },
  BIH: {
    gk: [
      { id: 'begovic', name: 'Asmir Begović', number: 1, club: 'Everton', age: 38 },
      { id: 'sehić', name: 'Adi Šehić', number: 12, club: 'Konyaspor', age: 30 },
      { id: 'piric', name: 'Kenan Piric', number: 23, club: 'Borac Banja Luka', age: 31 },
    ],
    def: [
      { id: 'kolasinac', name: 'Sead Kolašinac', number: 4, club: 'Marseille', age: 32 },
      { id: 'zukanovic', name: 'Ervin Zukanović', number: 5, club: 'Sarajevo', age: 38 },
      { id: 'kovacevic', name: 'Adnan Kovačević', number: 2, club: 'Sarajevo', age: 28 },
      { id: 'hadzikadunic', name: 'Dennis Hadžikadunić', number: 3, club: 'Rostov', age: 26 },
      { id: 'besic', name: 'Muhamed Bešić', number: 6, club: 'Kayserispor', age: 32 },
      { id: 'memic', name: 'Amir Memić', number: 13, club: 'Željezničar', age: 25 },
      { id: 'muharemovic', name: 'Tarik Muharemović', number: 14, club: 'Sion', age: 24 },
      { id: 'sanicic', name: 'Mateo Saničić', number: 22, club: 'Sarajevo', age: 23 },
    ],
    mid: [
      { id: 'pjanic', name: 'Miralem Pjanić', number: 15, club: 'Sharjah', age: 35 },
      { id: 'krusnica', name: 'Amar Krušnica', number: 8, club: 'Sarajevo', age: 24 },
      { id: 'tahirovic', name: 'Benjamin Tahirović', number: 7, club: 'Hoffenheim', age: 22 },
      { id: 'krunić', name: 'Rade Krunić', number: 16, club: 'Como', age: 31 },
      { id: 'gojak', name: 'Amer Gojak', number: 17, club: 'Dinamo Zagreb', age: 28 },
      { id: 'cimirot', name: 'Gojko Cimirot', number: 18, club: 'Konyaspor', age: 34 },
      { id: 'sulejmanovic', name: 'Admir Sulejmanović', number: 19, club: 'Sarajevo', age: 26 },
      { id: 'jusufovic', name: 'Haris Jusufović', number: 21, club: 'Sarajevo', age: 25 },
    ],
    fwd: [
      { id: 'dzeko', name: 'Edin Džeko', number: 11, club: 'Fiorentina', age: 40 },
      { id: 'demirovic', name: 'Ermedin Demirović', number: 9, club: 'Stuttgart', age: 27 },
      { id: 'rahimovic', name: 'Said Rahimović', number: 20, club: 'Sarajevo', age: 26 },
      { id: 'stevanovic', name: 'Miroslav Stevanović', number: 24, club: 'Servette', age: 34 },
      { id: 'prevljak', name: 'Smail Prevljak', number: 25, club: 'Kayserispor', age: 29 },
      { id: 'catić', name: 'Amar Ćatić', number: 26, club: 'Paderborn', age: 25 },
      { id: 'hodzic', name: 'Haris Hodžić', number: 10, club: 'Sarajevo', age: 27 },
    ],
  },
  SCO: {
    gk: [
      { id: 'gunn', name: 'Angus Gunn', number: 1, club: 'Norwich City', age: 30 },
      { id: 'gordon', name: 'Craig Gordon', number: 12, club: 'Hearts', age: 43 },
      { id: 'clark', name: 'Zander Clark', number: 23, club: 'Hearts', age: 32 },
    ],
    def: [
      { id: 'robertson', name: 'Andrew Robertson', number: 2, club: 'Liverpool', age: 32 },
      { id: 'tierney', name: 'Kieran Tierney', number: 3, club: 'Celtic', age: 28 },
      { id: 'hanley', name: 'Grant Hanley', number: 4, club: 'Bristol City', age: 34 },
      { id: 'porteous', name: 'Ryan Porteous', number: 5, club: 'Watford', age: 26 },
      { id: 'souttar', name: 'John Souttar', number: 6, club: 'Rangers', age: 29 },
      { id: 'mccrorie', name: 'Ross McCrorie', number: 13, club: 'Aberdeen', age: 27 },
      { id: 'hendry', name: 'Jack Hendry', number: 14, club: 'Qatar SC', age: 30 },
      { id: 'ralston', name: 'Anthony Ralston', number: 22, club: 'Celtic', age: 26 },
    ],
    mid: [
      { id: 'mcginn', name: 'John McGinn', number: 7, club: 'Aston Villa', age: 31 },
      { id: 'mcgregor', name: 'Callum McGregor', number: 8, club: 'Celtic', age: 32 },
      { id: 'gilmour', name: 'Billy Gilmour', number: 10, club: 'Napoli', age: 24 },
      { id: 'christie', name: 'Ryan Christie', number: 11, club: 'Bournemouth', age: 30 },
      { id: 'mclean', name: 'Kenny McLean', number: 16, club: 'Norwich City', age: 33 },
      { id: 'forrest', name: 'James Forrest', number: 17, club: 'Celtic', age: 34 },
      { id: 'armstrong', name: 'Stuart Armstrong', number: 18, club: 'Southampton', age: 33 },
      { id: 'mctominay', name: 'Scott McTominay', number: 15, club: 'Napoli', age: 29 },
    ],
    fwd: [
      { id: 'adams', name: 'Che Adams', number: 9, club: 'Torino', age: 29 },
      { id: 'dykes', name: 'Lyndon Dykes', number: 19, club: 'QPR', age: 30 },
      { id: 'shankland', name: 'Lawrence Shankland', number: 20, club: 'Club Brugge', age: 29 },
      { id: 'brown', name: 'Jacob Brown', number: 21, club: 'Luton Town', age: 27 },
      { id: 'nisbet', name: 'Kevin Nisbet', number: 24, club: 'Millwall', age: 28 },
      { id: 'morgan', name: 'Lewis Morgan', number: 25, club: 'New York Red Bulls', age: 28 },
      { id: 'fraser', name: 'Ryan Fraser', number: 26, club: 'Southampton', age: 31 },
    ],
  },
  HAI: {
    gk: [
      { id: 'placide', name: 'Johny Placide', number: 1, club: 'Valenciennes', age: 38 },
      { id: 'duverger', name: 'Josué Duverger', number: 12, club: 'Violette AC', age: 30 },
      { id: 'pierre', name: 'Alexandre Pierre', number: 23, club: 'Miami FC', age: 27 },
    ],
    def: [
      { id: 'etienne', name: 'Derrick Etienne', number: 2, club: 'LA Galaxy', age: 29 },
      { id: 'herivaux', name: 'Zachary Herivaux', number: 3, club: 'Rhode Island FC', age: 28 },
      { id: 'ade', name: 'Ricardo Adé', number: 4, club: 'Violette AC', age: 26 },
      { id: 'experience', name: 'Martin Experience', number: 5, club: 'Violette AC', age: 27 },
      { id: 'arcus', name: 'Carlens Arcus', number: 6, club: 'Brest', age: 29 },
      { id: 'metellus', name: 'Mickael Métellus', number: 13, club: 'Violette AC', age: 25 },
      { id: 'alceus', name: 'Bryan Alceus', number: 14, club: 'Violette AC', age: 30 },
      { id: 'pierre-d', name: 'Steeven Pierre', number: 22, club: 'Violette AC', age: 28 },
    ],
    mid: [
      { id: 'jocelyn', name: 'Steeven Jocelyn', number: 8, club: 'Violette AC', age: 26 },
      { id: 'bony', name: 'Djimy Bony', number: 10, club: 'Violette AC', age: 24 },
      { id: 'dubois', name: 'Widnyer Dubois', number: 11, club: 'Violette AC', age: 23 },
      { id: 'etienne-jr', name: 'Derrick Etienne Jr', number: 16, club: 'Atlético Ottawa', age: 27 },
      { id: 'woodly', name: 'Woodly Junior', number: 17, club: 'Violette AC', age: 25 },
      { id: 'monfrere', name: 'Dany Monfrere', number: 18, club: 'Violette AC', age: 24 },
      { id: 'alexandre', name: 'Alexandre Dumas', number: 19, club: 'Violette AC', age: 26 },
      { id: 'cantave', name: 'Jems Cantave', number: 21, club: 'Violette AC', age: 23 },
    ],
    fwd: [
      { id: 'pierrot', name: 'Frantzdy Pierrot', number: 9, club: 'Kasımpaşa', age: 28 },
      { id: 'nazon', name: 'Duckens Nazon', number: 7, club: 'Seraing', age: 28 },
      { id: 'christophe', name: 'Bryan Christophe', number: 20, club: 'Violette AC', age: 27 },
      { id: 'antoine', name: 'Carnejie Antoine', number: 24, club: 'Violette AC', age: 24 },
      { id: 'belfort', name: 'Wesley Belfort', number: 25, club: 'Violette AC', age: 26 },
      { id: 'guerrier', name: 'Kervens Guerrier', number: 26, club: 'Violette AC', age: 25 },
      { id: 'louis', name: 'Mondy Prunier', number: 15, club: 'Violette AC', age: 24 },
    ],
  },
  USA: {
    gk: [
      { id: 'turner', name: 'Matt Turner', number: 1, club: 'Nottingham Forest', age: 31 },
      { id: 'horvath', name: 'Ethan Horvath', number: 12, club: 'Cardiff City', age: 30 },
      { id: 'slonina', name: 'Gaga Slonina', number: 23, club: 'Chelsea', age: 21 },
    ],
    def: [
      { id: 'dest', name: 'Sergiño Dest', number: 2, club: 'PSV', age: 25 },
      { id: 'robinson', name: 'Antonee Robinson', number: 3, club: 'Fulham', age: 28 },
      { id: 'ream', name: 'Tim Ream', number: 4, club: 'Charlotte FC', age: 38 },
      { id: 'richards', name: 'Chris Richards', number: 5, club: 'Crystal Palace', age: 25 },
      { id: 'zimmerman', name: 'Walker Zimmerman', number: 6, club: 'Dallas', age: 32 },
      { id: 'palmer-brown', name: 'Erik Palmer-Brown', number: 13, club: 'Troyes', age: 28 },
      { id: 'scally', name: 'Joe Scally', number: 14, club: 'Borussia Mönchengladbach', age: 23 },
      { id: 'carter-vickers', name: 'Cameron Carter-Vickers', number: 22, club: 'Celtic', age: 28 },
    ],
    mid: [
      { id: 'pulisic', name: 'Christian Pulisic', number: 7, club: 'AC Milan', age: 27 },
      { id: 'mckennie', name: 'Weston McKennie', number: 8, club: 'Juventus', age: 27 },
      { id: 'musah', name: 'Yunus Musah', number: 10, club: 'AC Milan', age: 23 },
      { id: 'reyna', name: 'Gio Reyna', number: 11, club: 'Borussia Dortmund', age: 23 },
      { id: 'adams', name: 'Tyler Adams', number: 15, club: 'Bournemouth', age: 26 },
      { id: 'luna', name: 'Diego Luna', number: 16, club: 'Real Salt Lake', age: 21 },
      { id: 'de-la-torre', name: 'Luca de la Torre', number: 17, club: 'San Diego FC', age: 27 },
      { id: 'busio', name: 'Gianluca Busio', number: 18, club: 'Venezia', age: 23 },
    ],
    fwd: [
      { id: 'balogun', name: 'Folarin Balogun', number: 9, club: 'Monaco', age: 24 },
      { id: 'pepi', name: 'Ricardo Pepi', number: 19, club: 'PSV', age: 22 },
      { id: 'wright', name: 'Haji Wright', number: 20, club: 'Coventry City', age: 27 },
      { id: 'sargent', name: 'Josh Sargent', number: 21, club: 'Norwich City', age: 25 },
      { id: 'morris', name: 'Jordan Morris', number: 24, club: 'Seattle Sounders', age: 31 },
      { id: 'aaronson', name: 'Brenden Aaronson', number: 25, club: 'Leeds United', age: 24 },
      { id: 'tillman', name: 'Timothy Tillman', number: 26, club: 'LAFC', age: 26 },
    ],
  },
  AUS: {
    gk: [
      { id: 'ryan', name: 'Mathew Ryan', number: 1, club: 'Roma', age: 33 },
      { id: 'gauci', name: 'Joe Gauci', number: 12, club: 'Aston Villa', age: 25 },
      { id: 'vukovic', name: 'Danny Vukovic', number: 23, club: 'Central Coast Mariners', age: 39 },
    ],
    def: [
      { id: 'souttar', name: 'Harry Souttar', number: 2, club: 'Leicester City', age: 27 },
      { id: 'strain', name: 'Ryan Strain', number: 3, club: 'Saint-Étienne', age: 28 },
      { id: 'behich', name: 'Aziz Behich', number: 4, club: 'Melbourne City', age: 34 },
      { id: 'rowles', name: 'Kye Rowles', number: 5, club: 'Hearts', age: 26 },
      { id: 'atkinson', name: 'Nathaniel Atkinson', number: 6, club: 'Hearts', age: 26 },
      { id: 'grant', name: 'Rhyan Grant', number: 13, club: 'Sydney FC', age: 33 },
      { id: 'deng', name: 'Thomas Deng', number: 14, club: 'Albirex Niigata', age: 29 },
      { id: 'bos', name: 'Jordan Bos', number: 22, club: 'Westerlo', age: 23 },
    ],
    mid: [
      { id: 'irvine', name: 'Jackson Irvine', number: 8, club: 'St. Pauli', age: 32 },
      { id: 'metcalfe', name: 'Connor Metcalfe', number: 10, club: 'Hamburg', age: 25 },
      { id: 'baccus', name: 'Keanu Baccus', number: 11, club: 'St. Mirren', age: 27 },
      { id: 'oneill', name: 'Aiden O\'Neill', number: 16, club: 'Standard Liège', age: 27 },
      { id: 'mcgree', name: 'Riley McGree', number: 17, club: 'Middlesbrough', age: 26 },
      { id: 'goodwin', name: 'Craig Goodwin', number: 18, club: 'Adelaide United', age: 33 },
      { id: 'leckie', name: 'Mathew Leckie', number: 19, club: 'Melbourne City', age: 34 },
      { id: 'bozanic', name: 'Oliver Bozanic', number: 21, club: 'Central Coast Mariners', age: 35 },
    ],
    fwd: [
      { id: 'maclaren', name: 'Jamie Maclaren', number: 9, club: 'Mohun Bagan', age: 31 },
      { id: 'cummings', name: 'Jason Cummings', number: 20, club: 'Mohun Bagan', age: 30 },
      { id: 'borrello', name: 'Brandon Borrello', number: 24, club: 'Western Sydney', age: 30 },
      { id: 'duke', name: 'Mitchell Duke', number: 25, club: 'Machida Zelvia', age: 34 },
      { id: 'boyle', name: 'Martin Boyle', number: 26, club: 'Sydney FC', age: 31 },
      { id: 'surridge', name: 'Sam Surridge', number: 7, club: 'Portsmouth', age: 27 },
      { id: 'taggart', name: 'Adam Taggart', number: 15, club: 'Central Coast Mariners', age: 31 },
    ],
  },
  PAR: {
    gk: [
      { id: 'silva', name: 'Antony Silva', number: 1, club: 'Olimpia', age: 41 },
      { id: 'espinola', name: 'Juan Espínola', number: 12, club: 'Cerro Porteño', age: 30 },
      { id: 'ortiz', name: 'Gerardo Ortiz', number: 23, club: 'Libertad', age: 28 },
    ],
    def: [
      { id: 'gomez', name: 'Gustavo Gómez', number: 2, club: 'Palmeiras', age: 32 },
      { id: 'alonso', name: 'Júnior Alonso', number: 3, club: 'Krasnodar', age: 32 },
      { id: 'alderete', name: 'Omar Alderete', number: 4, club: 'Getafe', age: 29 },
      { id: 'rojas', name: 'Robert Rojas', number: 5, club: 'River Plate', age: 29 },
      { id: 'ramirez', name: 'Iván Ramírez', number: 6, club: 'Libertad', age: 28 },
      { id: 'espinoza', name: 'Matías Espinoza', number: 13, club: 'Libertad', age: 25 },
      { id: 'caceres', name: 'Juan Cáceres', number: 14, club: 'Libertad', age: 24 },
      { id: 'velazquez', name: 'Blas Riveros', number: 22, club: 'Braga', age: 27 },
    ],
    mid: [
      { id: 'almiron', name: 'Miguel Almirón', number: 10, club: 'Newcastle', age: 31 },
      { id: 'rojas-m', name: 'Matías Rojas', number: 8, club: 'Racing', age: 28 },
      { id: 'sanchez', name: 'Richard Sánchez', number: 11, club: 'América', age: 29 },
      { id: 'gomez-m', name: 'Diego Gómez', number: 16, club: 'Brighton', age: 22 },
      { id: 'galarza', name: 'Matías Galarza', number: 17, club: 'Vasco da Gama', age: 23 },
      { id: 'campuzano', name: 'Hernán Pérez', number: 18, club: 'Olimpia', age: 36 },
      { id: 'benitez', name: 'Julio Enciso', number: 19, club: 'Brighton', age: 22 },
      { id: 'cubas', name: 'Andrés Cubas', number: 21, club: 'Vancouver Whitecaps', age: 28 },
    ],
    fwd: [
      { id: 'sanabria', name: 'Antonio Sanabria', number: 9, club: 'Torino', age: 29 },
      { id: 'avalos', name: 'Gabriel Ávalos', number: 20, club: 'Argentinos Juniors', age: 34 },
      { id: 'arce', name: 'Alex Arce', number: 7, club: 'Libertad', age: 24 },
      { id: 'santacruz', name: 'Roque Santa Cruz', number: 24, club: 'Olimpia', age: 44 },
      { id: 'barboza', name: 'Federico Barboza', number: 25, club: 'Nacional', age: 26 },
      { id: 'nunez', name: 'Óscar Romero', number: 26, club: 'Cerro Porteño', age: 32 },
      { id: 'romero-p', name: 'Héctor Urbieta', number: 15, club: 'Sportivo Luqueño', age: 25 },
    ],
  },
  TUR: {
    gk: [
      { id: 'cakir', name: 'Uğurcan Çakır', number: 1, club: 'Trabzonspor', age: 30 },
      { id: 'gunok', name: 'Mert Günok', number: 12, club: 'Beşiktaş', age: 35 },
      { id: 'egribayat', name: 'İrfan Can Eğribayat', number: 23, club: 'Fenerbahçe', age: 26 },
    ],
    def: [
      { id: 'celik', name: 'Zeki Çelik', number: 2, club: 'Roma', age: 28 },
      { id: 'soyuncu', name: 'Çağlar Söyüncü', number: 3, club: 'Fenerbahçe', age: 29 },
      { id: 'demiral', name: 'Merih Demiral', number: 4, club: 'Al-Ahli', age: 27 },
      { id: 'kadioglu', name: 'Ferdi Kadıoğlu', number: 5, club: 'Brighton', age: 26 },
      { id: 'akaydin', name: 'Samet Akaydin', number: 6, club: 'Panathinaikos', age: 31 },
      { id: 'bardakci', name: 'Abdülkerim Bardakcı', number: 13, club: 'Galatasaray', age: 31 },
      { id: 'yilmaz-r', name: 'Rıdvan Yılmaz', number: 14, club: 'Beşiktaş', age: 24 },
      { id: 'muldur', name: 'Mert Müldür', number: 22, club: 'Sassuolo', age: 26 },
    ],
    mid: [
      { id: 'calhanoglu', name: 'Hakan Çalhanoğlu', number: 10, club: 'Inter Milan', age: 32 },
      { id: 'kahveci', name: 'İrfan Kahveci', number: 8, club: 'Fenerbahçe', age: 30 },
      { id: 'kokcu', name: 'Orkun Kökçü', number: 11, club: 'Benfica', age: 24 },
      { id: 'ozcan', name: 'Salih Özcan', number: 16, club: 'Borussia Dortmund', age: 27 },
      { id: 'yuksek', name: 'İsmail Yüksek', number: 17, club: 'Fenerbahçe', age: 26 },
      { id: 'guler', name: 'Arda Güler', number: 18, club: 'Real Madrid', age: 21 },
      { id: 'yildiz', name: 'Kenan Yıldız', number: 19, club: 'Juventus', age: 20 },
      { id: 'baryilmaz', name: 'Barış Alper Yılmaz', number: 21, club: 'Galatasaray', age: 25 },
    ],
    fwd: [
      { id: 'akturkoglu', name: 'Kerem Aktürkoğlu', number: 9, club: 'Benfica', age: 26 },
      { id: 'under', name: 'Cengiz Ünder', number: 7, club: 'Nice', age: 28 },
      { id: 'unal', name: 'Enes Ünal', number: 20, club: 'Getafe', age: 28 },
      { id: 'tosun', name: 'Cenk Tosun', number: 24, club: 'Beşiktaş', age: 34 },
      { id: 'yazici', name: 'Yusuf Yazıcı', number: 25, club: 'Lille', age: 28 },
      { id: 'aydin', name: 'Eren Aydın', number: 26, club: 'Fenerbahçe', age: 24 },
      { id: 'yilmaz-b', name: 'Burak Yılmaz', number: 15, club: 'Beşiktaş', age: 39 },
    ],
  },
  CIV: {
    gk: [
      { id: 'sangare-gk', name: 'Badra Ali Sangaré', number: 1, club: 'Portimonense', age: 28 },
      { id: 'fofana-gk', name: 'Yahia Fofana', number: 12, club: 'OH Leuven', age: 25 },
      { id: 'cisse', name: 'Aboubacar Cissé', number: 23, club: 'ASEC Mimosas', age: 27 },
    ],
    def: [
      { id: 'aurier', name: 'Serge Aurier', number: 2, club: 'Villarreal', age: 33 },
      { id: 'diomande', name: 'Ousmane Diomandé', number: 3, club: 'Sporting CP', age: 22 },
      { id: 'bailly', name: 'Eric Bailly', number: 4, club: 'Villarreal', age: 31 },
      { id: 'adingra', name: 'Simon Adingra', number: 5, club: 'Brighton', age: 23 },
      { id: 'konan', name: 'Ghislain Konan', number: 6, club: 'Al-Fayha', age: 29 },
      { id: 'boly', name: 'Willy Boly', number: 13, club: 'Nottingham Forest', age: 34 },
      { id: 'kossounou', name: 'Odilon Kossounou', number: 14, club: 'Atalanta', age: 24 },
      { id: 'masuaku', name: 'Arthur Masuaku', number: 22, club: 'Sunderland', age: 32 },
    ],
    mid: [
      { id: 'kessie', name: 'Franck Kessié', number: 8, club: 'Al-Ahli', age: 29 },
      { id: 'sangare', name: 'Ibrahim Sangaré', number: 10, club: 'Nottingham Forest', age: 27 },
      { id: 'fofana', name: 'Seko Fofana', number: 11, club: 'Al-Nassr', age: 30 },
      { id: 'seri', name: 'Jean Seri', number: 16, club: 'Hull City', age: 34 },
      { id: 'pepe', name: 'Nicolas Pépé', number: 17, club: 'Trabzonspor', age: 30 },
      { id: 'haller', name: 'Sébastien Haller', number: 18, club: 'Borussia Dortmund', age: 31 },
      { id: 'krasso', name: 'Jean-Philippe Krasso', number: 19, club: 'Saint-Étienne', age: 28 },
      { id: 'bamba-m', name: 'Christian Bamba', number: 21, club: 'Young Boys', age: 27 },
    ],
    fwd: [
      { id: 'zaha', name: 'Wilfried Zaha', number: 9, club: 'Charlotte FC', age: 33 },
      { id: 'traore', name: 'Adama Traoré', number: 7, club: 'Fulham', age: 29 },
      { id: 'diallo', name: 'Amad Diallo', number: 20, club: 'Manchester United', age: 23 },
      { id: 'bamba', name: 'Jonathan Bamba', number: 24, club: 'Lens', age: 29 },
      { id: 'guessand', name: 'Evann Guessand', number: 25, club: 'Nice', age: 24 },
      { id: 'boli', name: 'Franck Boli', number: 26, club: 'Akhmat Grozny', age: 31 },
      { id: 'boga', name: 'Jérémie Boga', number: 15, club: 'Nice', age: 28 },
    ],
  },
  ECU: {
    gk: [
      { id: 'dominguez', name: 'Alexander Domínguez', number: 1, club: 'LDU Quito', age: 38 },
      { id: 'galindez', name: 'Hernán Galíndez', number: 12, club: 'Aucas', age: 35 },
      { id: 'ramirez', name: 'Moises Ramírez', number: 23, club: 'Independiente del Valle', age: 25 },
    ],
    def: [
      { id: 'estupinan', name: 'Pervis Estupiñán', number: 2, club: 'Brighton', age: 28 },
      { id: 'hincapie', name: 'Piero Hincapié', number: 3, club: 'Bayer Leverkusen', age: 24 },
      { id: 'torres', name: 'Felix Torres', number: 4, club: 'Santos Laguna', age: 28 },
      { id: 'arboleda', name: 'Robert Arboleda', number: 5, club: 'São Paulo', age: 34 },
      { id: 'preciado', name: 'Angelo Preciado', number: 6, club: 'Genk', age: 27 },
      { id: 'hurtado', name: 'José Hurtado', number: 13, club: 'Independiente del Valle', age: 25 },
      { id: 'realpe', name: 'Leonardo Realpe', number: 14, club: 'Barcelona SC', age: 28 },
      { id: 'rodriguez', name: 'Kevin Rodríguez', number: 22, club: 'Union Saint-Gilloise', age: 25 },
    ],
    mid: [
      { id: 'caicedo', name: 'Moisés Caicedo', number: 8, club: 'Chelsea', age: 24 },
      { id: 'gruezo', name: 'Carlos Gruezo', number: 10, club: 'San Jose Earthquakes', age: 30 },
      { id: 'paez', name: 'Kendry Páez', number: 11, club: 'Chelsea', age: 18 },
      { id: 'mendez', name: 'Jhegson Méndez', number: 16, club: 'São Paulo', age: 28 },
      { id: 'cifuentes', name: 'José Cifuentes', number: 17, club: 'Rangers', age: 26 },
      { id: 'alcantara', name: 'Jerson Alcántara', number: 18, club: 'Barcelona SC', age: 26 },
      { id: 'sarmiento', name: 'Jeremy Sarmiento', number: 19, club: 'Brighton', age: 23 },
      { id: 'ibarra', name: 'Alan Franco', number: 21, club: 'Atlético Mineiro', age: 28 },
    ],
    fwd: [
      { id: 'valencia', name: 'Enner Valencia', number: 9, club: 'Internacional', age: 36 },
      { id: 'estrada', name: 'Michael Estrada', number: 20, club: 'CSKA Sofia', age: 29 },
      { id: 'campana', name: 'Jordy Alcívar', number: 7, club: 'LDU Quito', age: 26 },
      { id: 'mena', name: 'Ángel Mena', number: 24, club: 'León', age: 37 },
      { id: 'preciado-f', name: 'Ayrton Preciado', number: 25, club: 'Barcelona SC', age: 28 },
      { id: 'caicedo-f', name: 'Jordy Caicedo', number: 26, club: 'Barcelona SC', age: 27 },
      { id: 'plata', name: 'Willian Pacho', number: 15, club: 'PSG', age: 24 },
    ],
  },
  CUW: {
    gk: [
      { id: 'room', name: 'Eloy Room', number: 1, club: 'Pachuca', age: 35 },
      { id: 'carolina', name: 'Jurich Carolina', number: 12, club: 'Veerplegers FC', age: 28 },
      { id: 'bryson', name: 'Trevor Bryson', number: 23, club: 'SV Hubentut Fortuna', age: 26 },
    ],
    def: [
      { id: 'martina', name: 'Cuco Martina', number: 2, club: 'Sparta Rotterdam', age: 36 },
      { id: 'bonevacia', name: 'Roly Bonevacia', number: 3, club: 'Al-Faisaly', age: 33 },
      { id: 'gaari', name: 'Juriën Gaari', number: 4, club: 'Willem II', age: 30 },
      { id: 'floranus', name: 'Sherel Floranus', number: 5, club: 'Lommel SK', age: 28 },
      { id: 'kuwas', name: 'Brandley Kuwas', number: 6, club: 'NAC Breda', age: 32 },
      { id: 'eijma', name: 'Roshon van Eijma', number: 13, club: 'Almere City', age: 27 },
      { id: 'cummins', name: 'Geraldo Cummins', number: 14, club: 'SV Hubentut Fortuna', age: 29 },
      { id: 'oro', name: 'Tyrick Oro', number: 22, club: 'TOP Oss', age: 25 },
    ],
    mid: [
      { id: 'bacuna', name: 'Leandro Bacuna', number: 8, club: 'Dundee', age: 33 },
      { id: 'hooi', name: 'Elson Hooi', number: 10, club: 'Dundee', age: 31 },
      { id: 'kerk', name: 'Gyrano Kerk', number: 11, club: 'Aris', age: 29 },
      { id: 'antonia', name: 'Jarchinio Antonia', number: 16, club: 'Al-Orobah', age: 35 },
      { id: 'juninho', name: 'Juninho Bacuna', number: 17, club: 'Birmingham City', age: 27 },
      { id: 'chong', name: 'Tahith Chong', number: 18, club: 'Birmingham City', age: 25 },
      { id: 'summerville', name: 'Crysencio Summerville', number: 19, club: 'West Ham', age: 24 },
      { id: 'janga', name: 'Rangelo Janga', number: 21, club: 'FC Volendam', age: 30 },
    ],
    fwd: [
      { id: 'nepomuceno', name: 'Givaro Nepomuceno', number: 9, club: 'SV Hubentut Fortuna', age: 26 },
      { id: 'carmelia', name: 'Shanon Carmelia', number: 7, club: 'TOP Oss', age: 28 },
      { id: 'statie', name: 'Gino Statie', number: 20, club: 'FC Dordrecht', age: 28 },
      { id: 'bernardina', name: 'Ridge Bernadina', number: 24, club: 'Helmond Sport', age: 27 },
      { id: 'ebuehi', name: 'Tyronne Ebuehi', number: 25, club: 'Empoli', age: 30 },
      { id: 'prins', name: 'Aiko Prins', number: 26, club: 'Helmond Sport', age: 24 },
      { id: 'maria', name: 'Michael Maria', number: 15, club: 'FC Dordrecht', age: 26 },
    ],
  },
  JPN: {
    gk: [
      { id: 'gonda', name: 'Shuichi Gonda', number: 1, club: 'Shimizu S-Pulse', age: 36 },
      { id: 'schmidt', name: 'Daniel Schmidt', number: 12, club: 'Sint-Truiden', age: 32 },
      { id: 'suzuki-z', name: 'Zion Suzuki', number: 23, club: 'Parma', age: 23 },
    ],
    def: [
      { id: 'sakai', name: 'Hiroki Sakai', number: 2, club: 'Urawa Reds', age: 35 },
      { id: 'tomiyasu', name: 'Takehiro Tomiyasu', number: 3, club: 'Arsenal', age: 27 },
      { id: 'itakura', name: 'Ko Itakura', number: 4, club: 'Manchester City', age: 28 },
      { id: 'sugawara', name: 'Yukinari Sugawara', number: 5, club: 'Southampton', age: 25 },
      { id: 'muroya', name: 'Sei Muroya', number: 6, club: 'Melbourne City', age: 29 },
      { id: 'hiroki-ito', name: 'Hiroki Ito', number: 13, club: 'Stuttgart', age: 26 },
      { id: 'taniguchi', name: 'Shogo Taniguchi', number: 14, club: 'Al-Rayyan', age: 33 },
      { id: 'machida', name: 'Tsukasa Machida', number: 22, club: 'Red Star Belgrade', age: 32 },
    ],
    mid: [
      { id: 'kamada', name: 'Daichi Kamada', number: 8, club: 'Lazio', age: 28 },
      { id: 'endo', name: 'Wataru Endo', number: 10, club: 'Liverpool', age: 32 },
      { id: 'doan', name: 'Ritsu Doan', number: 11, club: 'Freiburg', age: 27 },
      { id: 'mitoma', name: 'Kaoru Mitoma', number: 16, club: 'Brighton', age: 28 },
      { id: 'asano', name: 'Takuma Asano', number: 17, club: 'Bochum', age: 30 },
      { id: 'junya-ito', name: 'Junya Ito', number: 18, club: 'Reims', age: 32 },
      { id: 'tanaka', name: 'Ao Tanaka', number: 19, club: 'Fortuna Düsseldorf', age: 27 },
      { id: 'hatate', name: 'Reo Hatate', number: 21, club: 'Celtic', age: 27 },
    ],
    fwd: [
      { id: 'kubo', name: 'Takefusa Kubo', number: 9, club: 'Real Sociedad', age: 24 },
      { id: 'maeda', name: 'Daizen Maeda', number: 7, club: 'Celtic', age: 27 },
      { id: 'furuhashi', name: 'Kyogo Furuhashi', number: 20, club: 'Celtic', age: 29 },
      { id: 'minamino', name: 'Takumi Minamino', number: 24, club: 'Monaco', age: 30 },
      { id: 'ueda', name: 'Ayase Ueda', number: 25, club: 'Feyenoord', age: 27 },
      { id: 'osako', name: 'Yuya Osako', number: 26, club: 'Vissel Kobe', age: 35 },
      { id: 'soma', name: 'Yuki Soma', number: 15, club: 'Nagoya Grampus', age: 28 },
    ],
  },
  SWE: {
    gk: [
      { id: 'olsen', name: 'Robin Olsen', number: 1, club: 'Aston Villa', age: 35 },
      { id: 'nordfeldt', name: 'Kristoffer Nordfeldt', number: 12, club: 'AIK', age: 33 },
      { id: 'johansson', name: 'Viktor Johansson', number: 23, club: 'Stoke City', age: 27 },
    ],
    def: [
      { id: 'lindelof', name: 'Victor Lindelöf', number: 2, club: 'Manchester United', age: 31 },
      { id: 'augustinsson', name: 'Ludwig Augustinsson', number: 3, club: 'Malmö', age: 31 },
      { id: 'helander', name: 'Filip Helander', number: 4, club: 'Rangers', age: 32 },
      { id: 'krafth', name: 'Emil Krafth', number: 5, club: 'Newcastle', age: 31 },
      { id: 'starfelt', name: 'Carl Starfelt', number: 6, club: 'Celta Vigo', age: 29 },
      { id: 'nelsson', name: 'Victor Nelsson', number: 13, club: 'Galatasaray', age: 26 },
      { id: 'ekdal-h', name: 'Hjalmar Ekdal', number: 14, club: 'Burnley', age: 26 },
      { id: 'holm', name: 'Adam Andersson', number: 22, club: 'Rosenborg', age: 28 },
    ],
    mid: [
      { id: 'forsberg', name: 'Emil Forsberg', number: 8, club: 'New York Red Bulls', age: 34 },
      { id: 'ekdal', name: 'Albin Ekdal', number: 10, club: 'Sampdoria', age: 36 },
      { id: 'kulusevski', name: 'Dejan Kulusevski', number: 11, club: 'Tottenham', age: 25 },
      { id: 'elanga', name: 'Anthony Elanga', number: 16, club: 'Nottingham Forest', age: 23 },
      { id: 'svanberg', name: 'Mattias Svanberg', number: 17, club: 'Bologna', age: 26 },
      { id: 'karlsson', name: 'Jesper Karlsson', number: 18, club: 'Bologna', age: 26 },
      { id: 'claesson', name: 'Sebastian Larsson', number: 19, club: 'AIK', age: 40 },
      { id: 'olsson', name: 'Simon Olsson', number: 21, club: 'IFK Norrköping', age: 25 },
    ],
    fwd: [
      { id: 'isak', name: 'Alexander Isak', number: 9, club: 'Newcastle', age: 26 },
      { id: 'gyokeres', name: 'Viktor Gyökeres', number: 7, club: 'Sporting CP', age: 27 },
      { id: 'berg', name: 'Marcus Berg', number: 20, club: 'IFK Göteborg', age: 38 },
      { id: 'quaison', name: 'Robin Quaison', number: 24, club: 'Al-Khaleej', age: 32 },
      { id: 'guidetti', name: 'John Guidetti', number: 25, club: 'AIK', age: 33 },
      { id: 'saleh', name: 'Yousef Saleh', number: 26, club: 'Hammarby', age: 24 },
      { id: 'compaore', name: 'Bilal Boutaïb', number: 15, club: 'IFK Göteborg', age: 25 },
    ],
  },
  TUN: {
    gk: [
      { id: 'hassen', name: 'Mouez Hassen', number: 1, club: 'Club Africain', age: 29 },
      { id: 'mathlouthi', name: 'Aymen Mathlouthi', number: 12, club: 'Étoile du Sahel', age: 40 },
      { id: 'ben-mustapha', name: 'Bechir Ben Mustapha', number: 23, club: 'Étoile du Sahel', age: 33 },
    ],
    def: [
      { id: 'drager', name: 'Mohamed Dräger', number: 2, club: 'Luzern', age: 28 },
      { id: 'ben-romdhane', name: 'Mohamed Ali Ben Romdhane', number: 3, club: 'Ferencváros', age: 26 },
      { id: 'talbi', name: 'Montassar Talbi', number: 4, club: 'Lorient', age: 27 },
      { id: 'meriah', name: 'Yassine Meriah', number: 5, club: 'Espérance', age: 32 },
      { id: 'maaloul', name: 'Ali Maaloul', number: 6, club: 'Étoile du Sahel', age: 35 },
      { id: 'kechrida', name: 'Wajdi Kechrida', number: 13, club: 'Étoile du Sahel', age: 29 },
      { id: 'machach', name: 'Aymen Machach', number: 14, club: 'Kasımpaşa', age: 28 },
      { id: 'ghandri', name: 'Nader Ghandri', number: 22, club: 'Club Africain', age: 28 },
    ],
    mid: [
      { id: 'skhiri', name: 'Ellyes Skhiri', number: 8, club: 'Eintracht Frankfurt', age: 30 },
      { id: 'laidouni', name: 'Aïssa Laïdouni', number: 10, club: 'Union Berlin', age: 28 },
      { id: 'khazri', name: 'Wahbi Khazri', number: 11, club: 'Montpellier', age: 34 },
      { id: 'rafia', name: 'Hamza Rafia', number: 16, club: 'Salernitana', age: 26 },
      { id: 'lahmar', name: 'Hamza Lahmar', number: 17, club: 'Espérance', age: 25 },
      { id: 'ben-slimane', name: 'Anis Ben Slimane', number: 18, club: 'Sheffield United', age: 24 },
      { id: 'sassi', name: 'Ferjani Sassi', number: 19, club: 'Étoile du Sahel', age: 32 },
      { id: 'msakni-m', name: 'Youssef Msakni', number: 21, club: 'Al-Arabi', age: 34 },
    ],
    fwd: [
      { id: 'jebali', name: 'Issam Jebali', number: 9, club: 'Union Berlin', age: 34 },
      { id: 'sliti', name: 'Naim Sliti', number: 7, club: 'Espérance', age: 32 },
      { id: 'mejbri', name: 'Hannibal Mejbri', number: 20, club: 'Burnley', age: 23 },
      { id: 'jaziri', name: 'Seifeddine Jaziri', number: 24, club: 'Zamalek', age: 32 },
      { id: 'jouini', name: 'Haythem Jouini', number: 25, club: 'Espérance', age: 28 },
      { id: 'khenissi', name: 'Taha Yassine Khenissi', number: 26, club: 'Espérance', age: 33 },
      { id: 'abdi', name: 'Wajdi Abdi', number: 15, club: 'Espérance', age: 27 },
    ],
  },
  IRN: {
    gk: [
      { id: 'beiranvand', name: 'Alireza Beiranvand', number: 1, club: 'Persepolis', age: 32 },
      { id: 'mazaheri', name: 'Rashid Mazaheri', number: 12, club: 'Gol Gohar', age: 35 },
      { id: 'hosseini-gk', name: 'Hossein Hosseini', number: 23, club: 'Esteghlal', age: 32 },
    ],
    def: [
      { id: 'beitashour', name: 'Steven Beitashour', number: 2, club: 'Colorado Rapids', age: 37 },
      { id: 'hosseini', name: 'Majid Hosseini', number: 3, club: 'Kayserispor', age: 29 },
      { id: 'kanani', name: 'Hossein Kanani', number: 4, club: 'Persepolis', age: 31 },
      { id: 'khalilzadeh', name: 'Shojae Khalilzadeh', number: 5, club: 'Tractor', age: 36 },
      { id: 'mohammadi', name: 'Milad Mohammadi', number: 6, club: 'Akhmat Grozny', age: 31 },
      { id: 'moharrami', name: 'Sadegh Moharrami', number: 13, club: 'Dinamo Zagreb', age: 28 },
      { id: 'rezaeian', name: 'Ramin Rezaeian', number: 14, club: 'Sepahan', age: 34 },
      { id: 'aghaei', name: 'Aref Aghaei', number: 22, club: 'Sepahan', age: 25 },
    ],
    mid: [
      { id: 'azmoun', name: 'Sardar Azmoun', number: 8, club: 'Olympiacos', age: 31 },
      { id: 'jahanbakhsh', name: 'Alireza Jahanbakhsh', number: 10, club: 'Feyenoord', age: 32 },
      { id: 'ghoddos', name: 'Samuel Ghoddos', number: 11, club: 'Brentford', age: 32 },
      { id: 'amiri', name: 'Vahid Amiri', number: 16, club: 'Persepolis', age: 36 },
      { id: 'gholizadeh', name: 'Ali Gholizadeh', number: 17, club: 'Charleroi', age: 29 },
      { id: 'torabi', name: 'Mehdi Torabi', number: 18, club: 'Persepolis', age: 30 },
      { id: 'ezatolahi', name: 'Saeid Ezatolahi', number: 19, club: 'Rostov', age: 29 },
      { id: 'nourollahi', name: 'Ahmad Nourollahi', number: 21, club: 'Sharjah', age: 32 },
    ],
    fwd: [
      { id: 'taremi', name: 'Mehdi Taremi', number: 9, club: 'Inter Milan', age: 33 },
      { id: 'rezaei', name: 'Kaveh Rezaei', number: 7, club: 'Charleroi', age: 32 },
      { id: 'sayyadmanesh', name: 'Allahyar Sayyadmanesh', number: 20, club: 'Hull City', age: 24 },
      { id: 'moghanlou', name: 'Shahriar Moghanlou', number: 24, club: 'Sepahan', age: 28 },
      { id: 'gholami', name: 'Aref Gholami', number: 25, club: 'Esteghlal', age: 26 },
      { id: 'shojaei', name: 'Masoud Shojaei', number: 26, club: 'Sepahan', age: 41 },
      { id: 'dabbagh', name: 'Kianoush Rahmati', number: 15, club: 'Sepahan', age: 27 },
    ],
  },
  EGY: {
    gk: [
      { id: 'elshenawy', name: 'Mohamed El Shenawy', number: 1, club: 'Al Ahly', age: 36 },
      { id: 'gabal', name: 'Mohamed Abou Gabal', number: 12, club: 'Zamalek', age: 36 },
      { id: 'sobhi-gk', name: 'Mohamed Sobhi', number: 23, club: 'Pyramids', age: 25 },
    ],
    def: [
      { id: 'hegazi', name: 'Ahmed Hegazi', number: 2, club: 'Al-Ittihad', age: 34 },
      { id: 'hany', name: 'Mohamed Hany', number: 3, club: 'Al Ahly', age: 28 },
      { id: 'ashraf', name: 'Ayman Ashraf', number: 4, club: 'Al Ahly', age: 34 },
      { id: 'fathy', name: 'Ahmed Fathy', number: 5, club: 'Future FC', age: 40 },
      { id: 'hamdy', name: 'Mahmoud Hamdy', number: 6, club: 'Zamalek', age: 30 },
      { id: 'abdelmonsef', name: 'Mohamed Abdelmonsef', number: 13, club: 'Pyramids', age: 32 },
      { id: 'kamal', name: 'Omar Kamal', number: 14, club: 'Al Ahly', age: 27 },
      { id: 'fotouh', name: 'Ahmed Abou El Fotouh', number: 22, club: 'Zamalek', age: 26 },
    ],
    mid: [
      { id: 'elneny', name: 'Mohamed Elneny', number: 8, club: 'Arsenal', age: 33 },
      { id: 'hamdy-a', name: 'Amr Hamdy', number: 10, club: 'Zamalek', age: 28 },
      { id: 'sobhi', name: 'Ramadan Sobhi', number: 11, club: 'Pyramids', age: 28 },
      { id: 'trezeguet', name: 'Trézéguet', number: 16, club: 'Al Ahly', age: 31 },
      { id: 'afsha', name: 'Mohamed Magdy Afsha', number: 17, club: 'Al Ahly', age: 29 },
      { id: 'emam', name: 'Emad El-Din Mosa', number: 18, club: 'Smouha', age: 27 },
      { id: 'zizo', name: 'Zizo', number: 19, club: 'Al Ahly', age: 29 },
      { id: 'fathy-m', name: 'Mohamed Fathy', number: 21, club: 'Zamalek', age: 28 },
    ],
    fwd: [
      { id: 'salah', name: 'Mohamed Salah', number: 9, club: 'Liverpool', age: 34 },
      { id: 'hassan', name: 'Mostafa Mohamed', number: 7, club: 'Nantes', age: 28 },
      { id: 'marmoush', name: 'Omar Marmoush', number: 20, club: 'Eintracht Frankfurt', age: 26 },
      { id: 'kouka', name: 'Ahmed Hassan Kouka', number: 24, club: 'Panathinaikos', age: 32 },
      { id: 'hamdy-f', name: 'Marwan Hamdy', number: 25, club: 'Smouha', age: 27 },
      { id: 'shahat', name: 'Hussein El Shahat', number: 26, club: 'Al Ahly', age: 33 },
      { id: 'bencharki', name: 'Achraf Bencharki', number: 15, club: 'Al Ahly', age: 31 },
    ],
  },
  NZL: {
    gk: [
      { id: 'sail', name: 'Oliver Sail', number: 1, club: 'Wellington Phoenix', age: 29 },
      { id: 'crocombe', name: 'Max Crocombe', number: 12, club: 'Mansfield Town', age: 30 },
      { id: 'moss', name: 'Glen Moss', number: 23, club: 'Auckland FC', age: 43 },
    ],
    def: [
      { id: 'boxall', name: 'Michael Boxall', number: 2, club: 'Minnesota United', age: 34 },
      { id: 'pijnaker', name: 'Nando Pijnaker', number: 3, club: 'Oxford United', age: 25 },
      { id: 'tuiloma', name: 'Bill Tuiloma', number: 4, club: 'Portland Timbers', age: 29 },
      { id: 'smith', name: 'Tommy Smith', number: 5, club: 'Burton Albion', age: 35 },
      { id: 'cacace', name: 'Liberato Cacace', number: 6, club: 'Wellington Phoenix', age: 24 },
      { id: 'james', name: 'Issaka James', number: 13, club: 'Auckland FC', age: 22 },
      { id: 'surman', name: 'Finn Surman', number: 14, club: 'Wellington Phoenix', age: 22 },
      { id: 'stanger', name: 'George Stanger', number: 22, club: 'Livingston', age: 25 },
    ],
    mid: [
      { id: 'rojas', name: 'Marco Rojas', number: 8, club: 'Auckland FC', age: 33 },
      { id: 'thomas', name: 'Ryan Thomas', number: 10, club: 'PEC Zwolle', age: 30 },
      { id: 'stamenic', name: 'Marko Stamenic', number: 11, club: 'Nottingham Forest', age: 23 },
      { id: 'singh', name: 'Sarpreet Singh', number: 16, club: 'Wellington Phoenix', age: 26 },
      { id: 'just', name: 'Elijah Just', number: 17, club: 'Auckland FC', age: 24 },
      { id: 'gleeson', name: 'Ben Gleeson', number: 18, club: 'Auckland FC', age: 23 },
      { id: 'payne', name: 'Clayton Lewis', number: 19, club: 'Western Sydney', age: 28 },
      { id: 'van-hattum', name: 'Oskar van Hattum', number: 21, club: 'Wellington Phoenix', age: 21 },
    ],
    fwd: [
      { id: 'wood', name: 'Chris Wood', number: 9, club: 'Nottingham Forest', age: 34 },
      { id: 'kuol', name: 'Garang Kuol', number: 7, club: 'Hamburger SV', age: 21 },
      { id: 'ingham', name: 'Dane Ingham', number: 20, club: 'Pafos', age: 26 },
      { id: 'barbarouses', name: 'Kosta Barbarouses', number: 24, club: 'Buriram United', age: 34 },
      { id: 'waine', name: 'Myles Kraev', number: 25, club: 'Auckland FC', age: 22 },
      { id: 'kraev', name: 'Ben Waine', number: 26, club: 'Wellington Phoenix', age: 23 },
      { id: 'old', name: 'Ben Old', number: 15, club: 'Portland Timbers', age: 22 },
    ],
  },
  KSA: {
    gk: [
      { id: 'owais', name: 'Mohammed Al-Owais', number: 1, club: 'Al Hilal', age: 34 },
      { id: 'aqidi', name: 'Nawaf Al-Aqidi', number: 12, club: 'Al Nassr', age: 26 },
      { id: 'najjar', name: 'Raghed Al-Najjar', number: 23, club: 'Al Ittihad', age: 27 },
    ],
    def: [
      { id: 'ghannam', name: 'Sultan Al-Ghannam', number: 2, club: 'Al Nassr', age: 31 },
      { id: 'bulaihi', name: 'Ali Al-Bulaihi', number: 3, club: 'Al Hilal', age: 36 },
      { id: 'tambakti', name: 'Hassan Tambakti', number: 4, club: 'Al Ittihad', age: 31 },
      { id: 'shahrani', name: 'Yasser Al-Shahrani', number: 5, club: 'Al Hilal', age: 33 },
      { id: 'breik', name: 'Mohammed Al-Breik', number: 6, club: 'Al Hilal', age: 32 },
      { id: 'amri', name: 'Abdulelah Al-Amri', number: 13, club: 'Al Nassr', age: 27 },
      { id: 'sahafi', name: 'Ziad Al-Sahafi', number: 14, club: 'Al Qadsiah', age: 25 },
      { id: 'harbi', name: 'Moteb Al-Harbi', number: 22, club: 'Al Fateh', age: 27 },
    ],
    mid: [
      { id: 'dawsari', name: 'Salem Al-Dawsari', number: 8, club: 'Al Hilal', age: 36 },
      { id: 'kanno', name: 'Mohammed Al-Kanno', number: 10, club: 'Al Nassr', age: 30 },
      { id: 'faraj', name: 'Salman Al-Faraj', number: 11, club: 'Al Hilal', age: 35 },
      { id: 'najei', name: 'Sami Al-Najei', number: 16, club: 'Al Nassr', age: 28 },
      { id: 'yahya', name: 'Ayman Yahya', number: 17, club: 'Al Nassr', age: 24 },
      { id: 'dawsari-n', name: 'Nasser Al-Dawsari', number: 18, club: 'Al Hilal', age: 26 },
      { id: 'khaibari', name: 'Abdullah Al-Khaibari', number: 19, club: 'Al Nassr', age: 28 },
      { id: 'abdulhamid', name: 'Saud Abdulhamid', number: 21, club: 'Roma', age: 26 },
    ],
    fwd: [
      { id: 'mitrovic', name: 'Aleksandar Mitrović', number: 9, club: 'Al Hilal', age: 31 },
      { id: 'buraik', name: 'Firas Al-Buraik', number: 7, club: 'Al Ahli', age: 30 },
      { id: 'shehri', name: 'Saleh Al-Shehri', number: 20, club: 'Al Hilal', age: 32 },
      { id: 'radif', name: 'Abdullah Radif', number: 24, club: 'Al Hilal', age: 22 },
      { id: 'muwallad', name: 'Fahad Al-Muwallad', number: 25, club: 'Al Qadsiah', age: 31 },
      { id: 'ghareeb', name: 'Abdulrahman Ghareeb', number: 26, club: 'Al Ahli', age: 27 },
      { id: 'hamdan', name: 'Abdullah Al-Hamdan', number: 15, club: 'Al Hilal', age: 25 },
    ],
  },
  CPV: {
    gk: [
      { id: 'vozinha', name: 'Vozinha', number: 1, club: 'Nacional', age: 39 },
      { id: 'marcio', name: 'Márcio Rosa', number: 12, club: 'Marítimo', age: 35 },
      { id: 'rosa', name: 'José Carlos Lopes', number: 23, club: 'Tondela', age: 30 },
    ],
    def: [
      { id: 'stopira', name: 'Stopira', number: 2, club: 'Feirense', age: 35 },
      { id: 'carlos', name: 'Carlos Ponck', number: 3, club: 'Arouca', age: 30 },
      { id: 'ponck', name: 'Diney', number: 4, club: 'Estoril', age: 32 },
      { id: 'diney', name: 'Jeffry Fortes', number: 5, club: 'Sparta Rotterdam', age: 36 },
      { id: 'fortes', name: 'Steven Fortès', number: 6, club: 'Estoril', age: 32 },
      { id: 'steven', name: 'Jójó', number: 13, club: 'Nacional', age: 30 },
      { id: 'jojo', name: 'Patrick Andrade', number: 14, club: 'Al Wahda', age: 32 },
      { id: 'andrade', name: 'Luís Rocha', number: 22, club: 'Nacional', age: 28 },
    ],
    mid: [
      { id: 'semedo', name: 'Nuno Rocha', number: 8, club: 'Ceará', age: 32 },
      { id: 'rocha', name: 'Platini', number: 10, club: 'Santa Clara', age: 37 },
      { id: 'platini', name: 'Ryan Mendes', number: 11, club: 'Al Nasr', age: 35 },
      { id: 'mendes', name: 'Jamiro Monteiro', number: 16, club: 'San Jose Earthquakes', age: 31 },
      { id: 'monteiro', name: 'Gege', number: 17, club: 'Nacional', age: 28 },
      { id: 'gege', name: 'Djaniny', number: 18, club: 'Al Jazira', age: 33 },
      { id: 'djaniny', name: 'Hélder Tavares', number: 19, club: 'Arouca', age: 31 },
      { id: 'tavares', name: 'Babanco', number: 21, club: 'Nacional', age: 34 },
    ],
    fwd: [
      { id: 'cabral', name: 'Júlio Tavares', number: 9, club: 'Al Fateh', age: 36 },
      { id: 'tavares-f', name: 'Willis Furtado', number: 7, club: 'Nacional', age: 34 },
      { id: 'furtado', name: 'Garry Rodrigues', number: 20, club: 'Al Ittihad', age: 35 },
      { id: 'rodrigues', name: 'Hélder Costa', number: 24, club: 'Leeds United', age: 30 },
      { id: 'costa', name: 'Lisandro López', number: 25, club: 'Estoril', age: 28 },
      { id: 'lopez', name: 'Willyan da Silva', number: 26, club: 'Nacional', age: 27 },
      { id: 'silva', name: 'Bébé', number: 15, club: 'Rayo Vallecano', age: 34 },
    ],
  },
  SEN: {
    gk: [
      { id: 'mendy', name: 'Édouard Mendy', number: 1, club: 'Al Ahli', age: 33 },
      { id: 'diouf', name: 'Seny Dieng', number: 12, club: 'Lorient', age: 31 },
      { id: 'dieng', name: 'Alfred Gomis', number: 23, club: 'Angers', age: 36 },
    ],
    def: [
      { id: 'koulibaly', name: 'Kalidou Koulibaly', number: 2, club: 'Al Hilal', age: 34 },
      { id: 'sabaly', name: 'Youssouf Sabaly', number: 3, club: 'Al Shabab', age: 32 },
      { id: 'diallo-b', name: 'Boubacar Baldé', number: 4, club: 'Brest', age: 27 },
      { id: 'balde', name: 'Abdou Diallo', number: 5, club: 'Al Arabi', age: 29 },
      { id: 'diallo-a', name: 'Pape Abou Cissé', number: 6, club: 'Olympiacos', age: 30 },
      { id: 'ballo-toure', name: 'Fodé Ballo-Touré', number: 13, club: 'Fulham', age: 28 },
      { id: 'jakobs', name: 'Ismaila Jakobs', number: 14, club: 'Monaco', age: 26 },
      { id: 'formose', name: 'Formose Mendy', number: 22, club: 'Brest', age: 30 },
    ],
    mid: [
      { id: 'gueye', name: 'Idrissa Gueye', number: 8, club: 'Everton', age: 36 },
      { id: 'sarr', name: 'Pape Matar Sarr', number: 10, club: 'Tottenham', age: 22 },
      { id: 'kouyate', name: 'Cheikh Kouyaté', number: 11, club: 'Nottingham Forest', age: 35 },
      { id: 'mendy-n', name: 'Nampalys Mendy', number: 16, club: 'Lens', age: 33 },
      { id: 'ndiaye', name: 'Iliman Ndiaye', number: 17, club: 'Everton', age: 25 },
      { id: 'camara', name: 'Lamine Camara', number: 18, club: 'Monaco', age: 21 },
      { id: 'mane', name: 'Sadio Mané', number: 19, club: 'Al Nassr', age: 34 },
      { id: 'diatta', name: 'Krepin Diatta', number: 21, club: 'Monaco', age: 26 },
    ],
    fwd: [
      { id: 'jackson', name: 'Nicolas Jackson', number: 9, club: 'Chelsea', age: 24 },
      { id: 'sarr-i', name: 'Ismaïla Sarr', number: 7, club: 'Crystal Palace', age: 27 },
      { id: 'diallo-m', name: 'Mamadou Diallo', number: 20, club: 'Toulouse', age: 22 },
      { id: 'diao', name: 'Habib Diallo', number: 24, club: 'Middlesbrough', age: 29 },
      { id: 'diallo-a-f', name: 'Amadou Diallo', number: 25, club: 'Toulouse', age: 24 },
      { id: 'seck', name: 'Moussa Ndiaye', number: 26, club: 'Anderlecht', age: 24 },
      { id: 'ndiaye-m', name: 'Pape Alassane Gueye', number: 15, club: 'Marseille', age: 26 },
    ],
  },
  NOR: {
    gk: [
      { id: 'nyland', name: 'Ørjan Nyland', number: 1, club: 'Sevilla', age: 35 },
      { id: 'jarstein', name: 'Rune Jarstein', number: 12, club: 'Viking', age: 40 },
      { id: 'kristiansen', name: 'Kristoffer Klaesson', number: 23, club: 'Leeds United', age: 24 },
    ],
    def: [
      { id: 'hovland', name: 'Stefan Hovland', number: 2, club: 'Club Brugge', age: 30 },
      { id: 'gabrielsen', name: 'André Hansen', number: 3, club: 'Rosenborg', age: 34 },
      { id: 'hansen', name: 'Fredrik Bjørkan', number: 4, club: 'Bodø/Glimt', age: 27 },
      { id: 'bjoran', name: 'Marcus Pedersen', number: 5, club: 'Torino', age: 25 },
      { id: 'pedersen', name: 'Leo Østigård', number: 6, club: 'Genoa', age: 25 },
      { id: 'ostigard', name: 'Julian Ryerson', number: 13, club: 'Borussia Dortmund', age: 27 },
      { id: 'ryerson', name: 'Felix Myhre', number: 14, club: 'Viking', age: 25 },
      { id: 'myhre', name: 'Kristoffer Ajer', number: 22, club: 'Brentford', age: 27 },
    ],
    mid: [
      { id: 'odegaard', name: 'Martin Ødegaard', number: 8, club: 'Arsenal', age: 27 },
      { id: 'berge', name: 'Sander Berge', number: 10, club: 'Fulham', age: 27 },
      { id: 'patrick-berg', name: 'Patrick Berg', number: 11, club: 'Bodø/Glimt', age: 27 },
      { id: 'aursnes', name: 'Fredrik Aursnes', number: 16, club: 'Benfica', age: 29 },
      { id: 'donnum', name: 'Aron Dønnum', number: 17, club: 'Toulouse', age: 26 },
      { id: 'thorstvedt', name: 'Kristian Thorstvedt', number: 18, club: 'Sassuolo', age: 25 },
      { id: 'hauge', name: 'Jens Petter Hauge', number: 19, club: 'Bodø/Glimt', age: 26 },
      { id: 'nusa', name: 'Antonio Nusa', number: 21, club: 'RB Leipzig', age: 20 },
    ],
    fwd: [
      { id: 'haaland', name: 'Erling Haaland', number: 9, club: 'Manchester City', age: 26 },
      { id: 'sorloth', name: 'Alexander Sørloth', number: 7, club: 'Atlético Madrid', age: 30 },
      { id: 'strand', name: 'Joshua King', number: 20, club: 'Fulham', age: 33 },
      { id: 'king', name: 'Erik Botheim', number: 24, club: 'Copenhagen', age: 25 },
      { id: 'botheim', name: 'Jørgen Strand Larsen', number: 25, club: 'Wolverhampton', age: 25 },
      { id: 'larsen', name: 'Sander Svendsen', number: 26, club: 'Viking', age: 27 },
      { id: 'svendsen', name: 'Arne Maøl', number: 15, club: 'Molde', age: 24 },
    ],
  },
  IRQ: {
    gk: [
      { id: 'jalal', name: 'Jalal Hassan', number: 1, club: 'Al Shorta', age: 32 },
      { id: 'yasin-gk', name: 'Ahmed Yasin', number: 12, club: 'Al Shorta', age: 33 },
      { id: 'hassan-gk', name: 'Hassan Ali', number: 23, club: 'Al Zawraa', age: 29 },
    ],
    def: [
      { id: 'adnan', name: 'Ali Adnan', number: 2, club: 'Al Shorta', age: 30 },
      { id: 'dokan', name: 'Dokan Aldin', number: 3, club: 'Al Zawraa', age: 28 },
      { id: 'ibrahim', name: 'Ahmed Ibrahim', number: 4, club: 'Al Shorta', age: 31 },
      { id: 'younis', name: 'Manaf Younis', number: 5, club: 'Al Quwa Al Jawiya', age: 27 },
      { id: 'hussein-d', name: 'Hussein Ali', number: 6, club: 'Al Shorta', age: 29 },
      { id: 'saadoon', name: 'Mustafa Saadoon', number: 13, club: 'Al Shorta', age: 26 },
      { id: 'faez', name: 'Ali Faez', number: 14, club: 'Al Shorta', age: 32 },
      { id: 'kadhim', name: 'Husam Kadhim', number: 22, club: 'Al Shorta', age: 28 },
    ],
    mid: [
      { id: 'atshan', name: 'Amjad Atshan', number: 8, club: 'Al Shorta', age: 30 },
      { id: 'sulaka', name: 'Rebin Sulaka', number: 10, club: 'Al Shorta', age: 29 },
      { id: 'tariq', name: 'Humam Tariq', number: 11, club: 'Al Quwa Al Jawiya', age: 28 },
      { id: 'zaid', name: 'Zaid Ahmed', number: 16, club: 'Al Shorta', age: 25 },
      { id: 'resan', name: 'Bashar Resan', number: 17, club: 'Al Shorta', age: 28 },
      { id: 'ahmad', name: 'Ahmad Ibrahim', number: 18, club: 'Al Shorta', age: 27 },
      { id: 'qasim', name: 'Mohammed Qasim', number: 19, club: 'Al Shorta', age: 26 },
      { id: 'hussein-m', name: 'Ali Hussein', number: 21, club: 'Al Shorta', age: 28 },
    ],
    fwd: [
      { id: 'mohanad', name: 'Mohanad Ali', number: 9, club: 'Al Shorta', age: 24 },
      { id: 'aymen', name: 'Aymen Hussein', number: 7, club: 'Al Shorta', age: 28 },
      { id: 'mahmoud', name: 'Mahmoud Mohammed', number: 20, club: 'Al Shorta', age: 26 },
      { id: 'hasan', name: 'Hasan Abdulkareem', number: 24, club: 'Al Shorta', age: 25 },
      { id: 'khalid', name: 'Khalid Mohammed', number: 25, club: 'Al Zawraa', age: 27 },
      { id: 'osama', name: 'Osama Rashid', number: 26, club: 'Al Shorta', age: 28 },
      { id: 'mustafa', name: 'Mustafa Mohammed', number: 15, club: 'Al Shorta', age: 24 },
    ],
  },
  AUT: {
    gk: [
      { id: 'lindner', name: 'Heinz Lindner', number: 1, club: 'Basel', age: 35 },
      { id: 'bachmann', name: 'Daniel Bachmann', number: 12, club: 'Watford', age: 30 },
      { id: 'hedl', name: 'Niklas Hedl', number: 23, club: 'Rapid Wien', age: 24 },
    ],
    def: [
      { id: 'alaba', name: 'David Alaba', number: 2, club: 'Real Madrid', age: 33 },
      { id: 'laimer', name: 'Konrad Laimer', number: 3, club: 'Bayern Munich', age: 28 },
      { id: 'dragovic', name: 'Aleksandar Dragović', number: 4, club: 'PAOK', age: 34 },
      { id: 'wober', name: 'Maximilian Wöber', number: 5, club: 'Werder Bremen', age: 27 },
      { id: 'lienhart', name: 'Philipp Lienhart', number: 6, club: 'Freiburg', age: 29 },
      { id: 'danso', name: 'Kevin Danso', number: 13, club: 'Lens', age: 27 },
      { id: 'daniliuc', name: 'Flavius Daniliuc', number: 14, club: 'Salernitana', age: 24 },
      { id: 'ulmer', name: 'Andreas Ulmer', number: 22, club: 'New York Red Bulls', age: 39 },
    ],
    mid: [
      { id: 'sabitzer', name: 'Marcel Sabitzer', number: 8, club: 'Borussia Dortmund', age: 31 },
      { id: 'baumgartner', name: 'Christoph Baumgartner', number: 10, club: 'RB Leipzig', age: 26 },
      { id: 'schlager', name: 'Xaver Schlager', number: 11, club: 'Wolfsburg', age: 28 },
      { id: 'grillitsch', name: 'Florian Grillitsch', number: 16, club: 'Ajax', age: 29 },
      { id: 'wimmer', name: 'Patrick Wimmer', number: 17, club: 'Wolfsburg', age: 23 },
      { id: 'schmid', name: 'Romano Schmid', number: 18, club: 'Werder Bremen', age: 25 },
      { id: 'seiwald', name: 'Nicolas Seiwald', number: 19, club: 'RB Leipzig', age: 24 },
      { id: 'demiral', name: 'Gernot Trauner', number: 21, club: 'Bochum', age: 33 },
    ],
    fwd: [
      { id: 'gregoritsch', name: 'Michael Gregoritsch', number: 9, club: 'Freiburg', age: 31 },
      { id: 'arnautovic', name: 'Marko Arnautović', number: 7, club: 'Inter Milan', age: 36 },
      { id: 'gruell', name: 'Marco Grüll', number: 20, club: 'Werder Bremen', age: 27 },
      { id: 'weimann', name: 'Andreas Weimann', number: 24, club: 'Stoke City', age: 33 },
      { id: 'onisiwo', name: 'Silvan Knasmüllner', number: 25, club: 'Rapid Wien', age: 32 },
      { id: 'djibril', name: 'Moussa Djibril', number: 26, club: 'Salzburg', age: 22 },
      { id: 'kalajdzic', name: 'Sasa Kalajdzic', number: 15, club: 'Wolverhampton', age: 28 },
    ],
  },
  ALG: {
    gk: [
      { id: 'mandrea', name: 'Anthony Mandrea', number: 1, club: 'Caen', age: 28 },
      { id: 'mbolhi', name: 'Raïs M\'Bolhi', number: 12, club: 'CR Belouizdad', age: 38 },
      { id: 'benbouzid', name: 'Moustapha Zeghba', number: 23, club: 'Damac', age: 33 },
    ],
    def: [
      { id: 'mandi', name: 'Aïssa Mandi', number: 2, club: 'Villarreal', age: 34 },
      { id: 'bensebaini', name: 'Ramy Bensebaini', number: 3, club: 'Borussia Dortmund', age: 30 },
      { id: 'atal', name: 'Youcef Atal', number: 4, club: 'Nice', age: 29 },
      { id: 'zeffane', name: 'Mehdi Zeffane', number: 5, club: 'USM Alger', age: 32 },
      { id: 'benlamri', name: 'Djamel Benlamri', number: 6, club: 'Al Shabab', age: 35 },
      { id: 'ghoulam', name: 'Faouzi Ghoulam', number: 13, club: 'Al Hilal', age: 34 },
      { id: 'bensaleh', name: 'Abdelkader Bensaleh', number: 14, club: 'USM Alger', age: 28 },
      { id: 'delort', name: 'Anthony Delort', number: 22, club: 'Toulouse', age: 33 },
    ],
    mid: [
      { id: 'bennacer', name: 'Ismaël Bennacer', number: 8, club: 'AC Milan', age: 28 },
      { id: 'mahrez', name: 'Riyad Mahrez', number: 10, club: 'Al Ahli', age: 34 },
      { id: 'bentaleb', name: 'Nabil Bentaleb', number: 11, club: 'Lille', age: 31 },
      { id: 'feghouli', name: 'Sofiane Feghouli', number: 16, club: 'Al Shabab', age: 35 },
      { id: 'aouar', name: 'Houssem Aouar', number: 17, club: 'Al Ittihad', age: 26 },
      { id: 'zorgane', name: 'Adem Zorgane', number: 18, club: 'Charleroi', age: 25 },
      { id: 'zerrouki', name: 'Ramiz Zerrouki', number: 19, club: 'Twente', age: 27 },
      { id: 'brahimi', name: 'Yacine Brahimi', number: 21, club: 'Al Rayyan', age: 35 },
    ],
    fwd: [
      { id: 'benrahma', name: 'Saïd Benrahma', number: 9, club: 'Al Hilal', age: 30 },
      { id: 'bounedjah', name: 'Baghdad Bounedjah', number: 7, club: 'Al Shabab', age: 33 },
      { id: 'slimani', name: 'Islam Slimani', number: 20, club: 'Anderlecht', age: 37 },
      { id: 'belaili', name: 'Youcef Belaïli', number: 24, club: 'Al Akhdoud', age: 33 },
      { id: 'ounas', name: 'Adam Ounas', number: 25, club: 'Lecce', age: 29 },
      { id: 'belkebla', name: 'Haris Belkebla', number: 26, club: 'Brest', age: 31 },
      { id: 'ghezzal', name: 'Adelkader Ghezzal', number: 15, club: 'Al Akhdoud', age: 32 },
    ],
  },
  JOR: {
    gk: [
      { id: 'layla', name: 'Yazid Abu Layla', number: 1, club: 'Al Wehdat', age: 32 },
      { id: 'yasin-j', name: 'Moataz Yasin', number: 12, club: 'Al Faisaly', age: 28 },
      { id: 'shafi', name: 'Amir Shafi', number: 23, club: 'Al Hussein', age: 38 },
    ],
    def: [
      { id: 'ajalin', name: 'Salem Al-Ajalin', number: 2, club: 'Al Wehdat', age: 30 },
      { id: 'abdelrahman', name: 'Baha Abdel-Rahman', number: 3, club: 'Al Faisaly', age: 29 },
      { id: 'abu-saleh', name: 'Husam Abu Saleh', number: 4, club: 'Al Wehdat', age: 27 },
      { id: 'haddad', name: 'Ihsan Haddad', number: 5, club: 'Al Faisaly', age: 28 },
      { id: 'bani-yaseen', name: 'Anas Bani Yaseen', number: 6, club: 'Al Hussein', age: 33 },
      { id: 'yazori', name: 'Hassan Al-Yazori', number: 13, club: 'Al Wehdat', age: 28 },
      { id: 'eze', name: 'Eze Jair', number: 14, club: 'Al Hussein', age: 26 },
      { id: 'abu-risha', name: 'Mohannad Abu Risha', number: 22, club: 'Al Faisaly', age: 25 },
    ],
    mid: [
      { id: 'bakhit', name: 'Yaseen Al-Bakhit', number: 8, club: 'Al Faisaly', age: 27 },
      { id: 'ayed', name: 'Rajaei Ayed', number: 10, club: 'Al Wehdat', age: 29 },
      { id: 'rawabdeh', name: 'Noor Al-Rawabdeh', number: 11, club: 'Al Wehdat', age: 26 },
      { id: 'nasasrah', name: 'Abdallah Nasasrah', number: 16, club: 'Al Wehdat', age: 27 },
      { id: 'khattab', name: 'Ibrahim Khattab', number: 17, club: 'Al Wehdat', age: 28 },
      { id: 'khazaleh', name: 'Yousef Khazaleh', number: 18, club: 'Al Faisaly', age: 26 },
      { id: 'bahram', name: 'Mahmoud Bahram', number: 19, club: 'Al Wehdat', age: 25 },
      { id: 'freeh', name: 'Mohammad Freeh', number: 21, club: 'Al Hussein', age: 27 },
    ],
    fwd: [
      { id: 'taamari', name: 'Mousa Al-Taamari', number: 9, club: 'Montpellier', age: 28 },
      { id: 'naimat', name: 'Yazan Al-Naimat', number: 7, club: 'Al Arabi', age: 25 },
      { id: 'mardi', name: 'Mahmoud Al-Mardi', number: 20, club: 'Al Wehdat', age: 28 },
      { id: 'olwan', name: 'Ali Olwan', number: 24, club: 'Al Faisaly', age: 25 },
      { id: 'eid', name: 'Ahmad Eid', number: 25, club: 'Al Wehdat', age: 26 },
      { id: 'rawashdeh', name: 'Yousef Rawashdeh', number: 26, club: 'Al Faisaly', age: 25 },
      { id: 'anas', name: 'Anas Ahmad', number: 15, club: 'Al Faisaly', age: 24 },
    ],
  },
  COL: {
    gk: [
      { id: 'ospina', name: 'David Ospina', number: 1, club: 'Al Nassr', age: 37 },
      { id: 'vargas', name: 'Camilo Vargas', number: 12, club: 'Atlas', age: 35 },
      { id: 'chunga', name: 'José Luis Chunga', number: 23, club: 'Junior', age: 32 },
    ],
    def: [
      { id: 'sanchez', name: 'Davinson Sánchez', number: 2, club: 'Galatasaray', age: 29 },
      { id: 'mina', name: 'Yerry Mina', number: 3, club: 'Cagliari', age: 31 },
      { id: 'lucumi', name: 'Jhon Lucumí', number: 4, club: 'Bologna', age: 27 },
      { id: 'mojica', name: 'Johan Mojica', number: 5, club: 'Zaragoza', age: 33 },
      { id: 'munoz', name: 'Daniel Muñoz', number: 6, club: 'Crystal Palace', age: 29 },
      { id: 'arias', name: 'Santiago Arias', number: 13, club: 'Birmingham City', age: 33 },
      { id: 'cuesta', name: 'Carlos Cuesta', number: 14, club: 'Genk', age: 26 },
      { id: 'reyes', name: 'Andrés Reyes', number: 22, club: 'Junior', age: 25 },
    ],
    mid: [
      { id: 'cuadrado', name: 'Juan Cuadrado', number: 8, club: 'Inter Milan', age: 37 },
      { id: 'barrios', name: 'Wilmar Barrios', number: 10, club: 'Zenit', age: 31 },
      { id: 'lerma', name: 'Jefferson Lerma', number: 11, club: 'Crystal Palace', age: 31 },
      { id: 'quintero', name: 'Juan Fernando Quintero', number: 16, club: 'Millonarios', age: 33 },
      { id: 'arias-m', name: 'Jhon Arias', number: 17, club: 'Fluminense', age: 28 },
      { id: 'rodriguez', name: 'James Rodríguez', number: 18, club: 'León', age: 34 },
      { id: 'carrascal', name: 'Jhon Jáder Durán', number: 19, club: 'Aston Villa', age: 21 },
      { id: 'rios', name: 'Yáser Asprilla', number: 21, club: 'Girona', age: 21 },
    ],
    fwd: [
      { id: 'diaz', name: 'Luis Díaz', number: 9, club: 'Liverpool', age: 28 },
      { id: 'falcao', name: 'Radamel Falcao', number: 7, club: 'Millonarios', age: 39 },
      { id: 'sinisterra', name: 'Luis Sinisterra', number: 20, club: 'Bournemouth', age: 26 },
      { id: 'borja', name: 'Miguel Borja', number: 24, club: 'River Plate', age: 32 },
      { id: 'zapata', name: 'Duván Zapata', number: 25, club: 'Torino', age: 34 },
      { id: 'borre', name: 'Rafael Santos Borré', number: 26, club: 'Internacional', age: 29 },
      { id: 'cordoba', name: 'Jhon Córdoba', number: 15, club: 'Krasnodar', age: 32 },
    ],
  },
  COD: {
    gk: [
      { id: 'kiassumbua', name: 'Joël Kiassumbua', number: 1, club: 'Sion', age: 32 },
      { id: 'mandanda', name: 'Parfait Mandanda', number: 12, club: 'Dunkerque', age: 35 },
      { id: 'kioko', name: 'Bravy Kioko', number: 23, club: 'TP Mazembe', age: 28 },
    ],
    def: [
      { id: 'mbemba', name: 'Chancel Mbemba', number: 2, club: 'Marseille', age: 30 },
      { id: 'luyindama', name: 'Christian Luyindama', number: 3, club: 'Standard Liège', age: 30 },
      { id: 'tisserand', name: 'Marcel Tisserand', number: 4, club: 'Kasımpaşa', age: 32 },
      { id: 'ikoko', name: 'Jordan Ikoko', number: 5, club: 'Ludogorets', age: 31 },
      { id: 'mpeko', name: 'Issama Mpeko', number: 6, club: 'TP Mazembe', age: 29 },
      { id: 'nsakala', name: 'Fabrice N\'Sakala', number: 13, club: 'Le Havre', age: 34 },
      { id: 'bangala', name: 'Yannick Bangala', number: 14, club: 'TP Mazembe', age: 27 },
      { id: 'masuaku', name: 'Arthur Masuaku', number: 22, club: 'Sunderland', age: 32 },
    ],
    mid: [
      { id: 'kakuta', name: 'Gael Kakuta', number: 8, club: 'Caykur Rizespor', age: 34 },
      { id: 'akolo', name: 'Chadrac Akolo', number: 10, club: 'VfB Stuttgart', age: 29 },
      { id: 'mpoku', name: 'Paul-José Mpoku', number: 11, club: 'Konyaspor', age: 33 },
      { id: 'bongonda', name: 'Theo Bongonda', number: 16, club: 'Standard Liège', age: 29 },
      { id: 'tshibola', name: 'Aaron Tshibola', number: 17, club: 'AEL Limassol', age: 31 },
      { id: 'mputu', name: 'Trésor Mputu', number: 18, club: 'TP Mazembe', age: 41 },
      { id: 'mulumbu', name: 'Youssouf Mulumbu', number: 19, club: 'Zulte Waregem', age: 38 },
      { id: 'ndombe', name: 'Chancel NDombe', number: 21, club: 'TP Mazembe', age: 28 },
    ],
    fwd: [
      { id: 'bakambu', name: 'Cédric Bakambu', number: 9, club: 'Betis', age: 34 },
      { id: 'wissa', name: 'Yoane Wissa', number: 7, club: 'Brentford', age: 29 },
      { id: 'botaka', name: 'Jordan Botaka', number: 20, club: 'KV Kortrijk', age: 31 },
      { id: 'mayele', name: 'Fiston Mayele', number: 24, club: 'Young Africans', age: 29 },
      { id: 'baningime', name: 'Beni Baningime', number: 25, club: 'Heart of Midlothian', age: 26 },
      { id: 'bolingi', name: 'Jordan Nkumu', number: 26, club: 'TP Mazembe', age: 27 },
      { id: 'elia', name: 'Meschak Elia', number: 15, club: 'Young Boys', age: 27 },
    ],
  },
  UZB: {
    gk: [
      { id: 'nesterov', name: 'Ignatiy Nesterov', number: 1, club: 'Pakhtakor', age: 37 },
      { id: 'nazarov', name: 'Vladimir Nazarov', number: 12, club: 'Navbahor', age: 32 },
      { id: 'tolaganov', name: 'Otabek To\'laganov', number: 23, club: 'Pakhtakor', age: 28 },
    ],
    def: [
      { id: 'krimets', name: 'Egor Krimets', number: 2, club: 'Pakhtakor', age: 35 },
      { id: 'tursunov-d', name: 'Sanjar Tursunov', number: 3, club: 'Navbahor', age: 30 },
      { id: 'shorakhmedov', name: 'Akmal Shorakhmedov', number: 4, club: 'Pakhtakor', age: 32 },
      { id: 'erkinov', name: 'Hojimat Erkinov', number: 5, club: 'Pakhtakor', age: 28 },
      { id: 'khusanov', name: 'Abdukodir Khusanov', number: 6, club: 'Manchester City', age: 21 },
      { id: 'yakhshibekov', name: 'Jasurbek Yakhshibekov', number: 13, club: 'Pakhtakor', age: 27 },
      { id: 'abdukhalikov', name: 'Zafarmurod Abdukhalikov', number: 14, club: 'Pakhtakor', age: 29 },
      { id: 'khamidov', name: 'Odil Khamidov', number: 22, club: 'Navbahor', age: 26 },
    ],
    mid: [
      { id: 'masharipov', name: 'Jaloliddin Masharipov', number: 8, club: 'Al Nassr', age: 28 },
      { id: 'hamrobekov', name: 'Odiljon Hamrobekov', number: 10, club: 'Kairat', age: 30 },
      { id: 'shukurov', name: 'Otabek Shukurov', number: 11, club: 'Pakhtakor', age: 29 },
      { id: 'jasur', name: 'Jasur Yakhshibekov', number: 16, club: 'Pakhtakor', age: 25 },
      { id: 'abdurakhimov', name: 'Bobir Abdurakhimov', number: 17, club: 'Pakhtakor', age: 27 },
      { id: 'nasriddinov', name: 'Utkirbek Nasriddinov', number: 18, club: 'Pakhtakor', age: 26 },
      { id: 'mirakbarov', name: 'Azizbek Turgunboev', number: 19, club: 'Pakhtakor', age: 28 },
      { id: 'rustamov-m', name: 'Sherzod Rustamov', number: 21, club: 'Pakhtakor', age: 27 },
    ],
    fwd: [
      { id: 'shomurodov', name: 'Eldor Shomurodov', number: 9, club: 'Roma', age: 30 },
      { id: 'sergeev', name: 'Igor Sergeev', number: 7, club: 'Pakhtakor', age: 30 },
      { id: 'khamdamov', name: 'Dostonbek Khamdamov', number: 20, club: 'Pakhtakor', age: 24 },
      { id: 'fozilov', name: 'Khozhimat Uktamov', number: 24, club: 'Pakhtakor', age: 27 },
      { id: 'karimov', name: 'Lazizbek Karimov', number: 25, club: 'Navbahor', age: 26 },
      { id: 'rustamov', name: 'Sherzod Karimov', number: 26, club: 'Pakhtakor', age: 27 },
      { id: 'dostonbek', name: 'Bobur Abdulkhamidov', number: 15, club: 'Pakhtakor', age: 24 },
    ],
  },
  PAN: {
    gk: [
      { id: 'mejia', name: 'Luis Mejía', number: 1, club: 'Nacional', age: 33 },
      { id: 'fajardo', name: 'José Fajardo', number: 12, club: 'Plaza Amador', age: 30 },
      { id: 'mosquera', name: 'Orlando Mosquera', number: 23, club: 'Saprissa', age: 28 },
    ],
    def: [
      { id: 'escobar', name: 'Fidel Escobar', number: 2, club: 'Saprissa', age: 31 },
      { id: 'cummings', name: 'Harold Cummings', number: 3, club: 'Saprissa', age: 33 },
      { id: 'murillo', name: 'Michael Murillo', number: 4, club: 'Houston Dynamo', age: 29 },
      { id: 'chen', name: 'Roberto Chen', number: 5, club: 'Universitario', age: 32 },
      { id: 'farina', name: 'Edgardo Fariña', number: 6, club: 'Tauro', age: 28 },
      { id: 'godoy-d', name: 'José Godoy', number: 13, club: 'Saprissa', age: 30 },
      { id: 'avila', name: 'Ricardo Ávila', number: 14, club: 'Plaza Amador', age: 27 },
      { id: 'benitez', name: 'Guillermo Benítez', number: 22, club: 'Tauro', age: 26 },
    ],
    mid: [
      { id: 'godoy', name: 'Aníbal Godoy', number: 8, club: 'Nashville SC', age: 35 },
      { id: 'quintero', name: 'Alberto Quintero', number: 10, club: 'Universitario', age: 37 },
      { id: 'torres', name: 'Gabriel Torres', number: 11, club: 'The Strongest', age: 36 },
      { id: 'rodriguez', name: 'José Luis Rodríguez', number: 16, club: 'Saprissa', age: 28 },
      { id: 'carrasquilla', name: 'Adalberto Carrasquilla', number: 17, club: 'Houston Dynamo', age: 26 },
      { id: 'diaz', name: 'Ismael Díaz', number: 18, club: 'Universidad de Chile', age: 28 },
      { id: 'blackburn', name: 'Rolando Blackburn', number: 19, club: 'The Strongest', age: 32 },
      { id: 'gutierrez', name: 'Jorge Gutiérrez', number: 21, club: 'Saprissa', age: 29 },
    ],
    fwd: [
      { id: 'tejada', name: 'Abdiel Tejada', number: 9, club: 'Houston Dynamo', age: 24 },
      { id: 'aguilar', name: 'Amilcar Aguilar', number: 7, club: 'Tauro', age: 25 },
      { id: 'ycaza', name: 'Edgar Ycaza', number: 20, club: 'Universitario', age: 27 },
      { id: 'buitrago', name: 'Ricardo Buitrago', number: 24, club: 'Tauro', age: 28 },
      { id: 'baloy', name: 'Javier Baloy', number: 25, club: 'Plaza Amador', age: 24 },
      { id: 'salinas', name: 'Alcides Barrantes', number: 26, club: 'Sporting San Miguelito', age: 28 },
      { id: 'nurse', name: 'Roberto Nurse', number: 15, club: 'Tauro', age: 35 },
    ],
  },
  GHA: {
    gk: [
      { id: 'ata-zigi', name: 'Lawrence Ati-Zigi', number: 1, club: 'St. Gallen', age: 28 },
      { id: 'ofori', name: 'Richard Ofori', number: 12, club: 'Kaizer Chiefs', age: 31 },
      { id: 'danlad', name: 'Ibrahim Danlad', number: 23, club: 'Asante Kotoko', age: 24 },
    ],
    def: [
      { id: 'amartey', name: 'Daniel Amartey', number: 2, club: 'Leicester City', age: 30 },
      { id: 'djiku', name: 'Alexander Djiku', number: 3, club: 'Fenerbahçe', age: 31 },
      { id: 'salisu', name: 'Mohammed Salisu', number: 4, club: 'Monaco', age: 26 },
      { id: 'rahman', name: 'Baba Rahman', number: 5, club: 'PAOK', age: 31 },
      { id: 'mensah', name: 'Gideon Mensah', number: 6, club: 'Bordeaux', age: 27 },
      { id: 'attamah', name: 'Joseph Attamah', number: 13, club: 'Kayserispor', age: 30 },
      { id: 'opoku', name: 'Nicholas Opoku', number: 14, club: 'Amiens', age: 28 },
      { id: 'lamptey', name: 'Tariq Lamptey', number: 22, club: 'Brighton', age: 25 },
    ],
    mid: [
      { id: 'partey', name: 'Thomas Partey', number: 8, club: 'Arsenal', age: 32 },
      { id: 'kudus', name: 'Mohammed Kudus', number: 10, club: 'West Ham', age: 25 },
      { id: 'ayew-a', name: 'André Ayew', number: 11, club: 'Le Havre', age: 36 },
      { id: 'fatawu', name: 'Abdul Fatawu', number: 16, club: 'Leicester City', age: 21 },
      { id: 'sulemana', name: 'Kamaldeen Sulemana', number: 17, club: 'Atalanta', age: 23 },
      { id: 'kyereh', name: 'Daniel-Kofi Kyereh', number: 18, club: 'Freiburg', age: 29 },
      { id: 'bukari', name: 'Osman Bukari', number: 19, club: 'Austin FC', age: 26 },
      { id: 'sowah', name: 'Kamal Sowah', number: 21, club: 'Club Brugge', age: 25 },
    ],
    fwd: [
      { id: 'williams-i', name: 'Inaki Williams', number: 9, club: 'Athletic Bilbao', age: 31 },
      { id: 'williams-n', name: 'Nico Williams', number: 7, club: 'Athletic Bilbao', age: 23 },
      { id: 'semenyo', name: 'Antoine Semenyo', number: 20, club: 'Bournemouth', age: 25 },
      { id: 'nuamah', name: 'Ernest Nuamah', number: 24, club: 'Lyon', age: 21 },
      { id: 'ayew-j', name: 'Jordan Ayew', number: 25, club: 'Leicester City', age: 34 },
      { id: 'boakye', name: 'Ernest Boateng', number: 26, club: 'Asante Kotoko', age: 22 },
      { id: 'jordan', name: 'Jordan Pierre', number: 15, club: 'Leicester City', age: 20 },
    ],
  },
};
