import type { SquadList } from '@/types';

export const SQUADS_TOP12: Record<string, SquadList> = {
  BRA: {
    gk: [
      { id: 'alisson', name: 'Alisson', number: 1, club: 'Liverpool', age: 32, apiId: 292 },
      { id: 'ederson', name: 'Ederson', number: 23, club: 'Man City', age: 31, apiId: 617 },
      { id: 'bento', name: 'Bento', number: 12, club: 'Al-Qadsiah', age: 28 },
    ],
    def: [
      { id: 'danilo', name: 'Danilo', number: 2, club: 'Juventus', age: 33 },
      { id: 'militao', name: 'Militão', number: 3, club: 'Real Madrid', age: 27, apiId: 2314 },
      { id: 'marquinhos', name: 'Marquinhos', number: 4, club: 'PSG', age: 30, apiId: 98 },
      { id: 'gabriel-magalhaes', name: 'Gabriel Magalhães', number: 6, club: 'Arsenal', age: 27 },
      { id: 'wendell', name: 'Wendell', number: 16, club: 'Porto', age: 31 },
      { id: 'guilherme-arana', name: 'Guilherme Arana', number: 13, club: 'Atletico MG', age: 27 },
      { id: 'alex-telles', name: 'Alex Telles', number: 14, club: 'Botafogo', age: 31 },
      { id: 'beraldo', name: 'Beraldo', number: 26, club: 'PSG', age: 20 },
    ],
    mid: [
      { id: 'casemiro', name: 'Casemiro', number: 5, club: 'Man Utd', age: 34 },
      { id: 'bruno-guimaraes', name: 'Bruno Guimarães', number: 8, club: 'Newcastle', age: 27 },
      { id: 'lucas-paqueta', name: 'Lucas Paquetá', number: 10, club: 'West Ham', age: 27 },
      { id: 'gerson', name: 'Gerson', number: 15, club: 'Flamengo', age: 27 },
      { id: 'andre', name: 'André', number: 17, club: 'Fulham', age: 23 },
      { id: 'douglas-luiz', name: 'Douglas Luiz', number: 18, club: 'Juventus', age: 26 },
      { id: 'yan-couto', name: 'Yan Couto', number: 22, club: 'Man City', age: 22 },
    ],
    fwd: [
      { id: 'vinicius-jr', name: 'Vinicius Jr', number: 7, club: 'Real Madrid', age: 24, apiId: 350 },
      { id: 'rodrygo', name: 'Rodrygo', number: 9, club: 'Real Madrid', age: 23, apiId: 1485 },
      { id: 'raphinha', name: 'Raphinha', number: 11, club: 'Barcelona', age: 28, apiId: 50002 },
      { id: 'savinho', name: 'Savinho', number: 19, club: 'Man City', age: 21 },
      { id: 'endrick', name: 'Endrick', number: 20, club: 'Real Madrid', age: 18 },
      { id: 'gabriel-martinelli', name: 'Gabriel Martinelli', number: 21, club: 'Arsenal', age: 23 },
      { id: 'pedro', name: 'Pedro', number: 24, club: 'Flamengo', age: 27 },
      { id: 'igor-jesus', name: 'Igor Jesus', number: 25, club: 'Botafogo', age: 23 },
    ],
  },
  FRA: {
    gk: [
      { id: 'maignan', name: 'Maignan', number: 1, club: 'AC Milan', age: 29 },
      { id: 'areola', name: 'Areola', number: 23, club: 'West Ham', age: 31 },
      { id: 'restes', name: 'Restes', number: 16, club: 'Lyon', age: 20 },
    ],
    def: [
      { id: 'pavard', name: 'Pavard', number: 2, club: 'Inter Milan', age: 29 },
      { id: 'kounde', name: 'Koundé', number: 5, club: 'Barcelona', age: 26 },
      { id: 'upamecano', name: 'Upamecano', number: 4, club: 'Bayern Munich', age: 26 },
      { id: 'saliba', name: 'Saliba', number: 17, club: 'Arsenal', age: 24 },
      { id: 't-hernandez', name: 'T.Hernández', number: 22, club: 'AC Milan', age: 28, apiId: 2295 },
      { id: 'clauss', name: 'Clauss', number: 25, club: 'Marseille', age: 32 },
      { id: 'kalulu', name: 'Kalulu', number: 13, club: 'Juventus', age: 23 },
      { id: 'lukeba', name: 'Lukeba', number: 26, club: 'RB Leipzig', age: 21 },
    ],
    mid: [
      { id: 'tchouameni', name: 'Tchouaméni', number: 8, club: 'Real Madrid', age: 25, apiId: 342524 },
      { id: 'rabiot', name: 'Rabiot', number: 14, club: 'Marseille', age: 30 },
      { id: 'fofana', name: 'Fofana', number: 6, club: 'Chelsea', age: 25 },
      { id: 'camavinga', name: 'Camavinga', number: 12, club: 'Real Madrid', age: 22, apiId: 342525 },
      { id: 'zaire-emery', name: 'Zaire-Emery', number: 18, club: 'PSG', age: 19 },
      { id: 'guendouzi', name: 'Guendouzi', number: 15, club: 'Marseille', age: 25 },
      { id: 'chotard', name: 'Chotard', number: 21, club: 'Montpellier', age: 23 },
      { id: 'kone', name: 'Koné', number: 9, club: 'Borussia Mönchengladbach', age: 23 },
    ],
    fwd: [
      { id: 'mbappe', name: 'Mbappé', number: 10, club: 'Real Madrid', age: 27, apiId: 278 },
      { id: 'dembele', name: 'Dembélé', number: 11, club: 'PSG', age: 27, apiId: 2098 },
      { id: 'griezmann', name: 'Griezmann', number: 7, club: 'Atletico Madrid', age: 35, apiId: 1784 },
      { id: 'thuram', name: 'Thuram', number: 9, club: 'Inter Milan', age: 27 },
      { id: 'kolo-muani', name: 'Kolo Muani', number: 20, club: 'Juventus', age: 26 },
      { id: 'coman', name: 'Coman', number: 3, club: 'Bayern Munich', age: 28 },
      { id: 'olise', name: 'Olise', number: 19, club: 'Bayern Munich', age: 23 },
    ],
  },
  ARG: {
    gk: [
      { id: 'martinez', name: 'Dibu Martínez', number: 23, club: 'Aston Villa', age: 32, apiId: 356670 },
      { id: 'rulli', name: 'Rulli', number: 12, club: 'Ajax', age: 31 },
      { id: 'musso', name: 'Musso', number: 1, club: 'Atalanta', age: 30 },
    ],
    def: [
      { id: 'montiel', name: 'Montiel', number: 4, club: 'Nottm Forest', age: 27 },
      { id: 'romero', name: 'Romero', number: 13, club: 'Tottenham', age: 26 },
      { id: 'otamendi', name: 'Otamendi', number: 19, club: 'Benfica', age: 36 },
      { id: 'lisandro-martinez', name: 'Lisandro Martínez', number: 6, club: 'Man Utd', age: 26 },
      { id: 'tagliafico', name: 'Tagliafico', number: 3, club: 'Lyon', age: 32 },
      { id: 'molina', name: 'Molina', number: 26, club: 'Atletico Madrid', age: 26 },
      { id: 'pezzella', name: 'Pezzella', number: 14, club: 'Real Betis', age: 33 },
      { id: 'acuna', name: 'Acuña', number: 8, club: 'Sevilla', age: 32 },
    ],
    mid: [
      { id: 'de-paul', name: 'De Paul', number: 7, club: 'Atletico Madrid', age: 30 },
      { id: 'mac-allister', name: 'Mac Allister', number: 20, club: 'Liverpool', age: 25, apiId: 265807 },
      { id: 'fernandez', name: 'Fernández', number: 24, club: 'Chelsea', age: 23 },
      { id: 'paredes', name: 'Paredes', number: 5, club: 'Roma', age: 31 },
      { id: 'lo-celso', name: 'Lo Celso', number: 18, club: 'Villarreal', age: 28 },
      { id: 'palacios', name: 'Palacios', number: 16, club: 'Leverkusen', age: 22 },
      { id: 'almada', name: 'Almada', number: 25, club: 'Atlanta United', age: 25 },
      { id: 'medina', name: 'Medina', number: 2, club: 'Lens', age: 24 },
    ],
    fwd: [
      { id: 'messi', name: 'Messi', number: 10, club: 'Inter Miami', age: 38, apiId: 154 },
      { id: 'alvarez', name: 'Álvarez', number: 9, club: 'Atletico Madrid', age: 24, apiId: 394413 },
      { id: 'dybala', name: 'Dybala', number: 21, club: 'Roma', age: 32 },
      { id: 'lautaro-martinez', name: 'Lautaro Martínez', number: 22, club: 'Inter Milan', age: 27 },
      { id: 'di-maria', name: 'Di María', number: 11, club: 'Benfica', age: 36 },
      { id: 'garnacho', name: 'Garnacho', number: 17, club: 'Man Utd', age: 20 },
      { id: 'soule', name: 'Soulé', number: 15, club: 'Roma', age: 21 },
    ],
  },
  ENG: {
    gk: [
      { id: 'pickford', name: 'Pickford', number: 1, club: 'Everton', age: 32, apiId: 2436 },
      { id: 'raya', name: 'Raya', number: 23, club: 'Arsenal', age: 29 },
      { id: 'henderson', name: 'Henderson', number: 13, club: 'Crystal Palace', age: 31 },
    ],
    def: [
      { id: 'alexander-arnold', name: 'Alexander-Arnold', number: 2, club: 'Real Madrid', age: 26, apiId: 18592 },
      { id: 'walker', name: 'Walker', number: 22, club: 'Man City', age: 36 },
      { id: 'guehi', name: 'Guehi', number: 6, club: 'Crystal Palace', age: 24 },
      { id: 'stones', name: 'Stones', number: 5, club: 'Man City', age: 32 },
      { id: 'colwill', name: 'Colwill', number: 26, club: 'Chelsea', age: 22 },
      { id: 'konsa', name: 'Konsa', number: 14, club: 'Aston Villa', age: 27 },
      { id: 'hall', name: 'Hall', number: 15, club: 'Chelsea', age: 21 },
      { id: 'trippier', name: 'Trippier', number: 12, club: 'Newcastle', age: 34 },
    ],
    mid: [
      { id: 'bellingham', name: 'Bellingham', number: 10, club: 'Real Madrid', age: 21, apiId: 1082 },
      { id: 'rice', name: 'Rice', number: 4, club: 'Arsenal', age: 27, apiId: 184941 },
      { id: 'mainoo', name: 'Mainoo', number: 8, club: 'Man Utd', age: 20, apiId: 394416 },
      { id: 'gallagher', name: 'Gallagher', number: 16, club: 'Chelsea', age: 25 },
      { id: 'curtis-jones', name: 'Curtis Jones', number: 17, club: 'Liverpool', age: 24 },
      { id: 'toney', name: 'Toney', number: 19, club: 'Al-Ahli', age: 29 },
      { id: 'wharton', name: 'Wharton', number: 25, club: 'Crystal Palace', age: 22 },
      { id: 'eze', name: 'Eze', number: 21, club: 'Crystal Palace', age: 27 },
    ],
    fwd: [
      { id: 'kane', name: 'Kane', number: 9, club: 'Bayern Munich', age: 32, apiId: 184942 },
      { id: 'saka', name: 'Saka', number: 7, club: 'Arsenal', age: 23, apiId: 218804 },
      { id: 'foden', name: 'Foden', number: 11, club: 'Man City', age: 26, apiId: 184943 },
      { id: 'gordon', name: 'Gordon', number: 20, club: 'Newcastle', age: 23 },
      { id: 'watkins', name: 'Watkins', number: 18, club: 'Aston Villa', age: 29 },
      { id: 'palmer', name: 'Palmer', number: 3, club: 'Chelsea', age: 23 },
      { id: 'rashford', name: 'Rashford', number: 24, club: 'Man Utd', age: 27, apiId: 184944 },
    ],
  },
  ESP: {
    gk: [
      { id: 'unai-simon', name: 'Unai Simón', number: 23, club: 'Athletic Club', age: 27 },
      { id: 'raya', name: 'Raya', number: 13, club: 'Arsenal', age: 29 },
      { id: 'arnau-tenas', name: 'Arnau Tenas', number: 1, club: 'PSG', age: 24 },
    ],
    def: [
      { id: 'carvajal', name: 'Carvajal', number: 2, club: 'Real Madrid', age: 32 },
      { id: 'le-normand', name: 'Le Normand', number: 4, club: 'Atletico Madrid', age: 28 },
      { id: 'laporte', name: 'Laporte', number: 14, club: 'Al-Nassr', age: 32 },
      { id: 'pau-cubarsi', name: 'Pau Cubarsí', number: 24, club: 'Barcelona', age: 18 },
      { id: 'grimaldo', name: 'Grimaldo', number: 22, club: 'Leverkusen', age: 29 },
      { id: 'alba', name: 'Alba', number: 18, club: 'Inter Miami', age: 35 },
      { id: 'pedro-porro', name: 'Pedro Porro', number: 20, club: 'Tottenham', age: 25 },
      { id: 'vivian', name: 'Vivian', number: 3, club: 'Athletic Club', age: 25 },
    ],
    mid: [
      { id: 'pedri', name: 'Pedri', number: 8, club: 'Barcelona', age: 23, apiId: 284177 },
      { id: 'rodri', name: 'Rodri', number: 16, club: 'Man City', age: 29, apiId: 284460 },
      { id: 'gavi', name: 'Gavi', number: 6, club: 'Barcelona', age: 22, apiId: 279600 },
      { id: 'merino', name: 'Merino', number: 5, club: 'Arsenal', age: 28 },
      { id: 'fabian-ruiz', name: 'Fabian Ruiz', number: 10, club: 'PSG', age: 28 },
      { id: 'zubimendi', name: 'Zubimendi', number: 12, club: 'Arsenal', age: 26 },
      { id: 'casado', name: 'Casadó', number: 15, club: 'Barcelona', age: 21 },
      { id: 'pepelu', name: 'Pepelu', number: 25, club: 'Valencia', age: 26 },
    ],
    fwd: [
      { id: 'yamal', name: 'Yamal', number: 19, club: 'Barcelona', age: 18, apiId: 279592 },
      { id: 'morata', name: 'Morata', number: 7, club: 'AC Milan', age: 33 },
      { id: 'williams', name: 'Williams', number: 11, club: 'Athletic Club', age: 22 },
      { id: 'dani-olmo', name: 'Dani Olmo', number: 21, club: 'Barcelona', age: 27 },
      { id: 'torres', name: 'Torres', number: 9, club: 'Barcelona', age: 25 },
      { id: 'oyarzabal', name: 'Oyarzabal', number: 17, club: 'Real Sociedad', age: 28 },
      { id: 'joselu', name: 'Joselu', number: 26, club: 'Maccabi Tel Aviv', age: 34 },
    ],
  },
  GER: {
    gk: [
      { id: 'neuer', name: 'Neuer', number: 1, club: 'Bayern Munich', age: 40 },
      { id: 'ter-stegen', name: 'ter Stegen', number: 22, club: 'Barcelona', age: 33 },
      { id: 'baumann', name: 'Baumann', number: 12, club: 'Hoffenheim', age: 34 },
    ],
    def: [
      { id: 'kimmich', name: 'Kimmich', number: 6, club: 'Bayern Munich', age: 29, apiId: 2083 },
      { id: 'rudiger', name: 'Rüdiger', number: 2, club: 'Real Madrid', age: 32 },
      { id: 'schlotterbeck', name: 'Schlotterbeck', number: 4, club: 'Dortmund', age: 28 },
      { id: 'tah', name: 'Tah', number: 5, club: 'Leverkusen', age: 30 },
      { id: 'raum', name: 'Raum', number: 3, club: 'RB Leipzig', age: 27 },
      { id: 'mittelstadt', name: 'Mittelstädt', number: 14, club: 'Stuttgart', age: 27 },
      { id: 'henrichs', name: 'Henrichs', number: 25, club: 'RB Leipzig', age: 27 },
      { id: 'anton', name: 'Anton', number: 26, club: 'Dortmund', age: 28 },
    ],
    mid: [
      { id: 'goretzka', name: 'Goretzka', number: 8, club: 'Bayern Munich', age: 30 },
      { id: 'gundogan', name: 'Gündogan', number: 21, club: 'Barcelona', age: 34 },
      { id: 'andrich', name: 'Andrich', number: 23, club: 'Leverkusen', age: 30 },
      { id: 'pavlovic', name: 'Pavlovic', number: 18, club: 'Bayern Munich', age: 20 },
      { id: 'gross', name: 'Gross', number: 16, club: 'Dortmund', age: 22 },
      { id: 'can', name: 'Can', number: 20, club: 'Dortmund', age: 32 },
      { id: 'stiller', name: 'Stiller', number: 24, club: 'Stuttgart', age: 23 },
      { id: 'fuehrich', name: 'Führich', number: 11, club: 'Stuttgart', age: 26 },
    ],
    fwd: [
      { id: 'musiala', name: 'Musiala', number: 10, club: 'Bayern Munich', age: 22, apiId: 303983 },
      { id: 'havertz', name: 'Havertz', number: 7, club: 'Arsenal', age: 26, apiId: 2299 },
      { id: 'wirtz', name: 'Wirtz', number: 17, club: 'Leverkusen', age: 22, apiId: 379452 },
      { id: 'gnabry', name: 'Gnabry', number: 13, club: 'Bayern Munich', age: 29 },
      { id: 'sane', name: 'Sané', number: 19, club: 'Bayern Munich', age: 30 },
      { id: 'fullkrug', name: 'Fullkrug', number: 9, club: 'West Ham', age: 32 },
      { id: 'adeyemi', name: 'Adeyemi', number: 11, club: 'Dortmund', age: 23 },
    ],
  },
  POR: {
    gk: [
      { id: 'diogo-costa', name: 'Diogo Costa', number: 1, club: 'Porto', age: 25 },
      { id: 'jose-sa', name: 'José Sá', number: 22, club: 'Wolves', age: 31 },
      { id: 'rui-silva', name: 'Rui Silva', number: 12, club: 'Betis', age: 30 },
    ],
    def: [
      { id: 'dalot', name: 'Dalot', number: 2, club: 'Man Utd', age: 25 },
      { id: 'ruben-dias', name: 'Rúben Dias', number: 4, club: 'Man City', age: 27, apiId: 2931 },
      { id: 'goncalo-inacio', name: 'Gonçalo Inácio', number: 5, club: 'Sporting', age: 23 },
      { id: 'antonio-silva', name: 'António Silva', number: 26, club: 'Benfica', age: 21 },
      { id: 'cancelo', name: 'Cancelo', number: 20, club: 'Barcelona', age: 31 },
      { id: 'nuno-mendes', name: 'Nuno Mendes', number: 19, club: 'PSG', age: 22 },
      { id: 'nelson-semedo', name: 'Nelson Semedo', number: 14, club: 'Wolves', age: 30 },
      { id: 'thierry-correia', name: 'Thierry Correia', number: 25, club: 'Valencia', age: 27 },
    ],
    mid: [
      { id: 'bruno-fernandes', name: 'Bruno Fernandes', number: 8, club: 'Man Utd', age: 30, apiId: 218 },
      { id: 'vitinha', name: 'Vitinha', number: 23, club: 'PSG', age: 25 },
      { id: 'palhinha', name: 'Palhinha', number: 6, club: 'Bayern Munich', age: 29 },
      { id: 'bernardo-silva', name: 'Bernardo Silva', number: 10, club: 'Man City', age: 29 },
      { id: 'joao-neves', name: 'João Neves', number: 16, club: 'PSG', age: 20 },
      { id: 'renato-sanches', name: 'Renato Sanches', number: 18, club: 'Benfica', age: 28 },
      { id: 'ruben-neves', name: 'Ruben Neves', number: 3, club: 'Al-Hilal', age: 27 },
      { id: 'otavio', name: 'Otávio', number: 24, club: 'Al-Nassr', age: 29 },
    ],
    fwd: [
      { id: 'ronaldo', name: 'Ronaldo', number: 7, club: 'Al-Nassr', age: 41 },
      { id: 'rafael-leao', name: 'Rafael Leão', number: 17, club: 'AC Milan', age: 25 },
      { id: 'diogo-jota', name: 'Diogo Jota', number: 21, club: 'Liverpool', age: 27 },
      { id: 'goncalo-ramos', name: 'Gonçalo Ramos', number: 9, club: 'PSG', age: 23 },
      { id: 'pedro-neto', name: 'Pedro Neto', number: 11, club: 'Chelsea', age: 24 },
      { id: 'francisco-conceicao', name: 'Francisco Conceição', number: 13, club: 'Juventus', age: 22 },
      { id: 'joao-felix', name: 'João Félix', number: 15, club: 'Chelsea', age: 26 },
    ],
  },
  NED: {
    gk: [
      { id: 'verbruggen', name: 'Verbruggen', number: 1, club: 'Brighton', age: 22 },
      { id: 'flekken', name: 'Flekken', number: 23, club: 'Brentford', age: 31 },
      { id: 'bijlow', name: 'Bijlow', number: 13, club: 'Feyenoord', age: 26 },
    ],
    def: [
      { id: 'van-dijk', name: 'Van Dijk', number: 4, club: 'Liverpool', age: 33, apiId: 282 },
      { id: 'de-ligt', name: 'De Ligt', number: 3, club: 'Man Utd', age: 24, apiId: 2421 },
      { id: 'timber', name: 'Timber', number: 2, club: 'Arsenal', age: 23 },
      { id: 'dumfries', name: 'Dumfries', number: 22, club: 'Inter Milan', age: 28, apiId: 342528 },
      { id: 'ake', name: 'Aké', number: 5, club: 'Man City', age: 29 },
      { id: 'geertruida', name: 'Geertruida', number: 19, club: 'RB Leipzig', age: 24 },
      { id: 'van-de-ven', name: 'Van de Ven', number: 25, club: 'Tottenham', age: 23 },
      { id: 'blind', name: 'Blind', number: 17, club: 'Girona', age: 34 },
    ],
    mid: [
      { id: 'de-jong', name: 'De Jong', number: 21, club: 'Barcelona', age: 27 },
      { id: 'reijnders', name: 'Reijnders', number: 14, club: 'AC Milan', age: 26 },
      { id: 'schouten', name: 'Schouten', number: 8, club: 'Bologna', age: 27 },
      { id: 'veerman', name: 'Veerman', number: 6, club: 'PSV', age: 26 },
      { id: 'koopmeiners', name: 'Koopmeiners', number: 20, club: 'Juventus', age: 26 },
      { id: 'gravenberch', name: 'Gravenberch', number: 16, club: 'Liverpool', age: 22 },
      { id: 'wieffer', name: 'Wieffer', number: 24, club: 'Brighton', age: 24 },
      { id: 'taylor', name: 'Taylor', number: 26, club: 'Feyenoord', age: 26 },
    ],
    fwd: [
      { id: 'gakpo', name: 'Gakpo', number: 18, club: 'Liverpool', age: 26, apiId: 341003 },
      { id: 'depay', name: 'Depay', number: 10, club: 'Atletico Madrid', age: 31 },
      { id: 'simons', name: 'Simons', number: 7, club: 'PSG', age: 22 },
      { id: 'zirkzee', name: 'Zirkzee', number: 9, club: 'Man Utd', age: 23 },
      { id: 'malen', name: 'Malen', number: 11, club: 'Dortmund', age: 26 },
      { id: 'weghorst', name: 'Weghorst', number: 12, club: 'Hoffenheim', age: 32 },
      { id: 'brobbey', name: 'Brobbey', number: 15, club: 'Ajax', age: 22 },
    ],
  },
  BEL: {
    gk: [
      { id: 'casteels', name: 'Casteels', number: 1, club: 'Al-Qadsiah', age: 32 },
      { id: 'mignolet', name: 'Mignolet', number: 13, club: 'Club Brugge', age: 36 },
      { id: 'vandevoordt', name: 'Vandevoordt', number: 12, club: 'RB Leipzig', age: 22 },
    ],
    def: [
      { id: 'castagne', name: 'Castagne', number: 21, club: 'Fulham', age: 29 },
      { id: 'faes', name: 'Faes', number: 4, club: 'Leicester', age: 27 },
      { id: 'theate', name: 'Theate', number: 3, club: 'Rennes', age: 24 },
      { id: 'debast', name: 'Debast', number: 2, club: 'Sporting', age: 21 },
      { id: 'meunier', name: 'Meunier', number: 15, club: 'Club Brugge', age: 32 },
      { id: 'vertonghen', name: 'Vertonghen', number: 5, club: 'Anderlecht', age: 37 },
      { id: 'de-cuyper', name: 'De Cuyper', number: 22, club: 'Club Brugge', age: 24 },
      { id: 'sardella', name: 'Sardella', number: 25, club: 'Anderlecht', age: 24 },
    ],
    mid: [
      { id: 'de-bruyne', name: 'De Bruyne', number: 7, club: 'Man City', age: 35, apiId: 627 },
      { id: 'tielemans', name: 'Tielemans', number: 8, club: 'Aston Villa', age: 29 },
      { id: 'onana', name: 'Onana', number: 6, club: 'Aston Villa', age: 28 },
      { id: 'mangala', name: 'Mangala', number: 14, club: 'Eintracht', age: 26 },
      { id: 'vanaken', name: 'Vanaken', number: 20, club: 'Club Brugge', age: 32 },
      { id: 'verschaeren', name: 'Verschaeren', number: 16, club: 'Anderlecht', age: 23 },
      { id: 'vermeeren', name: 'Vermeeren', number: 18, club: 'RB Leipzig', age: 20 },
      { id: 'engvall', name: 'Engels', number: 26, club: 'Celtic', age: 24 },
    ],
    fwd: [
      { id: 'lukaku', name: 'Lukaku', number: 10, club: 'Roma', age: 31 },
      { id: 'doku', name: 'Doku', number: 11, club: 'Man City', age: 22 },
      { id: 'trossard', name: 'Trossard', number: 9, club: 'Arsenal', age: 29 },
      { id: 'de-ketelaere', name: 'De Ketelaere', number: 17, club: 'Atalanta', age: 23 },
      { id: 'openda', name: 'Openda', number: 19, club: 'RB Leipzig', age: 24 },
      { id: 'bakayoko', name: 'Bakayoko', number: 24, club: 'Atletico Madrid', age: 22 },
      { id: 'batshuayi', name: 'Batshuayi', number: 23, club: 'Fenerbahce', age: 31 },
    ],
  },
  MAR: {
    gk: [
      { id: 'bounou', name: 'Bounou', number: 1, club: 'Al-Hilal', age: 33 },
      { id: 'munir', name: 'Munir', number: 12, club: 'Nice', age: 30 },
      { id: 'el-kajoui', name: 'El Kajoui', number: 23, club: 'RS Berkane', age: 33 },
    ],
    def: [
      { id: 'hakimi', name: 'Hakimi', number: 2, club: 'PSG', age: 27, apiId: 347318 },
      { id: 'saiss', name: 'Saiss', number: 6, club: 'Besiktas', age: 34 },
      { id: 'aguerd', name: 'Aguerd', number: 5, club: 'West Ham', age: 28 },
      { id: 'mazraoui', name: 'Mazraoui', number: 15, club: 'Man Utd', age: 27 },
      { id: 'attiat-allah', name: 'Attiat-Allah', number: 22, club: 'Wydad', age: 28 },
      { id: 'dari', name: 'Dari', number: 4, club: 'Rennes', age: 25 },
      { id: 'el-yamiq', name: 'El Yamiq', number: 3, club: 'Real Valladolid', age: 33 },
      { id: 'bouchouari', name: 'Bouchouari', number: 14, club: 'Sturm Graz', age: 23 },
    ],
    mid: [
      { id: 'amrabat', name: 'Amrabat', number: 4, club: 'Fiorentina', age: 28 },
      { id: 'ounahi', name: 'Ounahi', number: 8, club: 'Marseille', age: 24 },
      { id: 'el-khannouss', name: 'El Khannouss', number: 19, club: 'Leicester', age: 21 },
      { id: 'bouaddi', name: 'Bouaddi', number: 25, club: 'Lille', age: 17 },
      { id: 'richardson', name: 'Richardson', number: 16, club: 'Al-Ahli', age: 24 },
      { id: 'belkharcha', name: 'Belkharcha', number: 17, club: 'Wydad', age: 25 },
      { id: 'sabiri', name: 'Sabiri', number: 10, club: 'Sampdoria', age: 27 },
      { id: 'benali', name: 'Benali', number: 24, club: 'Stuttgart', age: 24 },
    ],
    fwd: [
      { id: 'ziyech', name: 'Ziyech', number: 7, club: 'Galatasaray', age: 32, apiId: 143234 },
      { id: 'en-nesyri', name: 'En-Nesyri', number: 9, club: 'Fenerbahce', age: 27, apiId: 283480 },
      { id: 'diaz', name: 'Diaz', number: 11, club: 'Real Madrid', age: 25 },
      { id: 'rahimi', name: 'Rahimi', number: 13, club: 'Al-Ain', age: 25 },
      { id: 'ez-abde', name: 'Ez Abde', number: 18, club: 'Osasuna', age: 23 },
      { id: 'benrahma', name: 'Benrahma', number: 20, club: 'Lyon', age: 29 },
      { id: 'akhomach', name: 'Akhomach', number: 21, club: 'Villarreal', age: 22 },
    ],
  },
  CRO: {
    gk: [
      { id: 'livakovic', name: 'Livaković', number: 1, club: 'Fenerbahce', age: 29, apiId: 126366 },
      { id: 'grbic', name: 'Grbić', number: 12, club: 'Atletico Madrid', age: 26 },
      { id: 'ivusic', name: 'Ivušić', number: 23, club: 'Osijek', age: 29 },
    ],
    def: [
      { id: 'juranovic', name: 'Juranović', number: 2, club: 'Union Berlin', age: 29 },
      { id: 'erlic', name: 'Erlić', number: 5, club: 'Sassuolo', age: 26 },
      { id: 'sutalo', name: 'Šutalo', number: 24, club: 'Ajax', age: 24 },
      { id: 'gvardiol', name: 'Gvardiol', number: 20, club: 'Man City', age: 22, apiId: 394414 },
      { id: 'sosa', name: 'Sosa', number: 19, club: 'Stuttgart', age: 26 },
      { id: 'stanisic', name: 'Stanišić', number: 22, club: 'Leverkusen', age: 24 },
      { id: 'pongracic', name: 'Pongračić', number: 3, club: 'Fiorentina', age: 27 },
      { id: 'caleta-car', name: 'Caleta-Car', number: 14, club: 'Southampton', age: 28 },
    ],
    mid: [
      { id: 'modric', name: 'Modrić', number: 10, club: 'Real Madrid', age: 41, apiId: 184 },
      { id: 'brozovic', name: 'Brozović', number: 11, club: 'Al-Nassr', age: 32 },
      { id: 'kovacic', name: 'Kovačić', number: 8, club: 'Man City', age: 30 },
      { id: 'sucic', name: 'Sučić', number: 13, club: 'RB Salzburg', age: 22 },
      { id: 'majer', name: 'Majer', number: 7, club: 'Rennes', age: 26 },
      { id: 'ivanusec', name: 'Ivanušec', number: 17, club: 'Feyenoord', age: 25 },
      { id: 'vlasic', name: 'Vlašić', number: 6, club: 'Torino', age: 27 },
      { id: 'pasalic-m', name: 'Pjaca', number: 26, club: 'Rijeka', age: 29 },
    ],
    fwd: [
      { id: 'perisic', name: 'Perišić', number: 4, club: 'Hajduk Split', age: 35 },
      { id: 'kramaric', name: 'Kramarić', number: 9, club: 'Hoffenheim', age: 33 },
      { id: 'pasalic', name: 'Pašalić', number: 16, club: 'Atalanta', age: 29 },
      { id: 'budimir', name: 'Budimir', number: 15, club: 'Osasuna', age: 32 },
      { id: 'livaja', name: 'Livaja', number: 18, club: 'Hajduk Split', age: 31 },
      { id: 'baturina', name: 'Baturina', number: 25, club: 'Dinamo Zagreb', age: 22 },
      { id: 'matanovic', name: 'Matanović', number: 21, club: 'Eintracht', age: 22 },
    ],
  },
  URU: {
    gk: [
      { id: 'rochet', name: 'Rochet', number: 1, club: 'Inter Milan', age: 27 },
      { id: 'muslera', name: 'Muslera', number: 12, club: 'Galatasaray', age: 38 },
      { id: 'israel', name: 'Israel', number: 23, club: 'Independiente', age: 24 },
    ],
    def: [
      { id: 'gimenez', name: 'Giménez', number: 2, club: 'Atletico Madrid', age: 29 },
      { id: 'araujo', name: 'Araújo', number: 4, club: 'Barcelona', age: 25 },
      { id: 'olivera', name: 'Olivera', number: 16, club: 'Napoli', age: 27 },
      { id: 'vina', name: 'Viña', number: 17, club: 'Flamengo', age: 26 },
      { id: 'nandez', name: 'Nández', number: 22, club: 'Cagliari', age: 28 },
      { id: 'bueno', name: 'Bueno', number: 13, club: 'Wolves', age: 22 },
      { id: 'caceres', name: 'Cáceres', number: 3, club: 'LA Galaxy', age: 37 },
      { id: 'saracchi', name: 'Saracchi', number: 15, club: 'River Plate', age: 26 },
    ],
    mid: [
      { id: 'valverde', name: 'Valverde', number: 8, club: 'Real Madrid', age: 27 },
      { id: 'bentancur', name: 'Bentancur', number: 6, club: 'Tottenham', age: 27 },
      { id: 'ugarte', name: 'Ugarte', number: 5, club: 'PSG', age: 23 },
      { id: 'de-arrascaeta', name: 'De Arrascaeta', number: 10, club: 'Flamengo', age: 30 },
      { id: 'pellistri', name: 'Pellistri', number: 11, club: 'Man Utd', age: 22 },
      { id: 'canobbio', name: 'Canobbio', number: 18, club: 'Athletico Paranaense', age: 27 },
      { id: 'vecino', name: 'Vecino', number: 24, club: 'Lazio', age: 34 },
      { id: 'martinez-g', name: 'Martínez', number: 25, club: 'Boca Juniors', age: 24 },
    ],
    fwd: [
      { id: 'suarez', name: 'Suárez', number: 9, club: 'Inter Miami', age: 39 },
      { id: 'nunez', name: 'Núñez', number: 19, club: 'Liverpool', age: 27 },
      { id: 'torres', name: 'Torres', number: 21, club: 'Orlando City', age: 26 },
      { id: 'ocampo', name: 'Ocampo', number: 20, club: 'River Plate', age: 25 },
      { id: 'de-la-cruz', name: 'De La Cruz', number: 7, club: 'Flamengo', age: 27 },
      { id: 'araujo-m', name: 'Araújo M.', number: 14, club: 'Peñarol', age: 22 },
      { id: 'rodriguez', name: 'Rodríguez', number: 25, club: 'Bahia', age: 25 },
    ],
  },
};
