import type { Team, Player, Stadium, Group } from '@/types';

export const TEAMS: Team[] = [
  {
    id: 'BRA', name: 'Brazil', flag: '🇧🇷', rating: 92, rank: 1, group: 'A',
    coach: 'Dorival Jr', mascot: 'Canarinho', style: 'Joga Bonito — flair, pressing, quick transitions',
    founded: 1914, titles: 5, finals: 7, semifinals: 11, bestResult: 'Champions (1958,1962,1970,1994,2002)',
    facts: [
      'Only nation to play in every single World Cup (22 editions)',
      'Their 7-1 loss to Germany in 2014 on home soil is called "The Mineirazo"',
      'Pelé won the WC at just 17 years old in 1958',
      'Yellow kit was banned in domestic football after 1950 final loss to Uruguay',
      'Ronaldo (R9) scored 8 goals in 2002 WC to claim the Golden Boot',
    ],
    players: [],
  },
  {
    id: 'FRA', name: 'France', flag: '🇫🇷', rating: 90, rank: 2, group: 'B',
    coach: 'Didier Deschamps', mascot: 'Footix the rooster', style: 'Defensive solidity with lightning counter-attack',
    founded: 1904, titles: 2, finals: 3, semifinals: 6, bestResult: 'Champions (1998, 2018)',
    facts: [
      'Youngest WC winning squad ever in 2018 — average age 26.1',
      'Mbappé was only 19 in the 2018 final when he scored',
      'The 2022 final vs Argentina is the most-watched sporting event ever',
      'Only team to win WC after the host nation also won',
    ],
    players: [],
  },
  {
    id: 'ARG', name: 'Argentina', flag: '🇦🇷', rating: 89, rank: 3, group: 'B',
    coach: 'Lionel Scaloni', mascot: 'Pibe de Oro', style: 'Counter-press with Messi pulling strings from deep',
    founded: 1893, titles: 3, finals: 5, semifinals: 6, bestResult: 'Champions (1978, 1986, 2022)',
    facts: [
      'Messi finally won the WC in 2022 at age 35 — his fifth attempt',
      'The 1986 "Hand of God" goal by Maradona is the most controversial in WC history',
      'Lost 3 consecutive finals (1990, 2014, 2022) before winning the third',
      'Argentina fans travel in the largest numbers of any WC team',
    ],
    players: [],
  },
  {
    id: 'ENG', name: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', rating: 84, rank: 5, group: 'C',
    coach: 'Gareth Southgate', mascot: 'Three Lions', style: 'Possession with explosive pace on the wings',
    founded: 1863, titles: 1, finals: 1, semifinals: 4, bestResult: 'Champions (1966, home soil)',
    facts: [
      '"It\'s coming home" became a global meme in 2018',
      'England invented football in 1863 — but have only won once',
      'Lost penalty shoot-outs in 1990, 1996, 1998, 2006, 2021',
      'Gareth Southgate himself missed the crucial penalty in Euro 1996',
    ],
    players: [],
  },
  {
    id: 'ESP', name: 'Spain', flag: '🇪🇸', rating: 85, rank: 6, group: 'C',
    coach: 'Luis de la Fuente', mascot: 'Naranjito the orange', style: 'Tiki-taka evolved — high tempo positional play',
    founded: 1909, titles: 1, finals: 1, semifinals: 5, bestResult: 'Champions (2010)',
    facts: [
      'Won Euro 2024 — first nation to win 4 European Championships',
      'Xavi and Iniesta never lost a single WC game while both were playing',
      'Yamal was born the day of the 2007 Champions League final',
      'Iniesta scored the winning goal in the 116th minute of the 2010 final',
    ],
    players: [],
  },
  {
    id: 'GER', name: 'Germany', flag: '🇩🇪', rating: 85, rank: 4, group: 'A',
    coach: 'Julian Nagelsmann', mascot: 'Paule the eagle', style: 'Gegenpressing with technical midfield control',
    founded: 1900, titles: 4, finals: 8, semifinals: 13, bestResult: 'Champions (1954,1974,1990,2014)',
    facts: [
      'Germany is the only nation to win the WC in 3 different decades',
      'The 7-1 vs Brazil in 2014 semi-final is the biggest upset in WC history',
      'Miroslav Klose holds the all-time WC goal record with 16 goals',
      'Lost to South Korea in 2018 group stage — most shocking WC exit ever',
    ],
    players: [],
  },
  {
    id: 'POR', name: 'Portugal', flag: '🇵🇹', rating: 86, rank: 7, group: 'D',
    coach: 'Roberto Martínez', mascot: 'Quinas eagle', style: 'Technical possession with explosive wide play',
    titles: 0, finals: 0, semifinals: 4, bestResult: 'Third place (1966)',
    facts: ['Cristiano Ronaldo holds the all-time international goals record', 'Euro 2016 champions — beat France in the final in Paris'],
    players: [],
  },
  {
    id: 'NED', name: 'Netherlands', flag: '🇳🇱', rating: 84, rank: 8, group: 'D',
    coach: 'Ronald Koeman', mascot: 'Leo the Lion', style: 'Total Football — fluid positioning and relentless pressing',
    titles: 0, finals: 3, semifinals: 5, bestResult: 'Runners-up (1974, 1978, 2010)',
    facts: ['Inventors of Total Football under Rinus Michels', 'Three-time finalists who have never won the World Cup'],
    players: [],
  },
  {
    id: 'BEL', name: 'Belgium', flag: '🇧🇪', rating: 81, rank: 9, group: 'E',
    coach: 'Domenico Tedesco', mascot: 'Red Devil', style: 'Counter-attacking with elite individual talent',
    titles: 0, finals: 0, semifinals: 2, bestResult: 'Third place (2018)',
    facts: ['Golden generation peaked at #1 FIFA ranking for 4 years', 'Only country where French and Dutch football culture collide'],
    players: [],
  },
  {
    id: 'CRO', name: 'Croatia', flag: '🇭🇷', rating: 83, rank: 10, group: 'F',
    coach: 'Zlatko Dalić', mascot: 'Vatreni', style: 'Midfield-dominant possession with tireless running',
    titles: 0, finals: 1, semifinals: 3, bestResult: 'Runners-up (2018)',
    facts: ['Population of just 4 million — smallest nation to reach a WC final', 'Luka Modrić won the Golden Ball in 2018'],
    players: [],
  },
  {
    id: 'URU', name: 'Uruguay', flag: '🇺🇾', rating: 80, rank: 11, group: 'E',
    coach: 'Marcelo Bielsa', mascot: 'Charrúa', style: 'Garra Charrúa — fighting spirit with tactical discipline',
    titles: 2, finals: 2, semifinals: 5, bestResult: 'Champions (1930, 1950)',
    facts: ['Hosted and won the very first World Cup in 1930', 'The 1950 Maracanazo against Brazil is football\'s greatest upset'],
    players: [],
  },
  {
    id: 'COL', name: 'Colombia', flag: '🇨🇴', rating: 79, rank: 12, group: 'F',
    coach: 'Néstor Lorenzo', mascot: 'El Cóndor', style: 'Creative flair with explosive attacking transitions',
    titles: 0, finals: 0, semifinals: 1, bestResult: 'Quarterfinals (2014)',
    facts: ['James Rodríguez won the 2014 Golden Boot with 6 goals', 'Copa América 2024 finalists — rising force in South America'],
    players: [],
  },
  {
    id: 'USA', name: 'United States', flag: '🇺🇸', rating: 76, rank: 13, group: 'G',
    coach: 'Gregg Berhalter', mascot: 'Sam the Eagle', style: 'High-energy pressing with young, fearless talent',
    titles: 0, finals: 0, semifinals: 1, bestResult: 'Third place (1930)',
    facts: ['Co-hosting the 2026 World Cup — biggest sporting event in US history', 'Beat England 1-0 in the 1950 WC — one of football\'s great shocks'],
    players: [],
  },
  {
    id: 'MEX', name: 'Mexico', flag: '🇲🇽', rating: 74, rank: 14, group: 'G',
    coach: 'Jaime Lozano', mascot: 'Kin the axolotl', style: 'Technical short-passing game with passionate support',
    titles: 0, finals: 0, semifinals: 2, bestResult: 'Quarterfinals (1970, 1986)',
    facts: ['Have been eliminated in the Round of 16 in seven consecutive World Cups', 'Azteca is the only stadium to host two WC finals'],
    players: [],
  },
  {
    id: 'JPN', name: 'Japan', flag: '🇯🇵', rating: 77, rank: 15, group: 'A',
    coach: 'Hajime Moriyasu', mascot: 'Captain Tsubasa', style: 'Disciplined pressing with rapid combination play',
    titles: 0, finals: 0, semifinals: 0, bestResult: 'Quarterfinals (2022)',
    facts: ['Beat both Germany and Spain in the 2022 group stage', 'Fans clean the stadium after every match — a beloved tradition'],
    players: [],
  },
  {
    id: 'SEN', name: 'Senegal', flag: '🇸🇳', rating: 76, rank: 16, group: 'B',
    coach: 'Aliou Cissé', mascot: 'Teranga Lion', style: 'Physical, fast, and direct with explosive pace up front',
    titles: 0, finals: 0, semifinals: 0, bestResult: 'Quarterfinals (2002)',
    facts: ['Beat France 1-0 in the 2002 WC opener — the biggest upset of the tournament', 'AFCON 2021 champions — first-ever continental title'],
    players: [],
  },
  {
    id: 'SUI', name: 'Switzerland', flag: '🇨🇭', rating: 78, rank: 17, group: 'G',
    coach: 'Murat Yakın', mascot: 'Alpenball', style: 'Organized defensive block with sharp counter-attacks',
    titles: 0, finals: 0, semifinals: 1, bestResult: 'Quarterfinals (1934, 1938, 1954, 2024)',
    facts: ['UEFA HQ is in Switzerland — football\'s bureaucratic heartland', 'Eliminated Italy from Euro 2024 with a dominant performance'],
    players: [],
  },
  {
    id: 'MAR', name: 'Morocco', flag: '🇲🇦', rating: 78, rank: 18, group: 'C',
    coach: 'Walid Regragui', mascot: 'Atlas Lion', style: 'Fearless defensive wall with lethal set-pieces',
    titles: 0, finals: 0, semifinals: 1, bestResult: 'Fourth place (2022)',
    facts: ['First African and Arab nation to reach a WC semifinal in 2022', 'Conceded just one goal (an own goal) in five knockout matches'],
    players: [],
  },
  {
    id: 'DEN', name: 'Denmark', flag: '🇩🇰', rating: 77, rank: 19, group: 'H',
    coach: 'Kasper Hjulmand', mascot: 'Viking Warrior', style: 'Compact defensive shape with intelligent pressing triggers',
    titles: 0, finals: 0, semifinals: 0, bestResult: 'Quarterfinals (1998)',
    facts: ['Won Euro 1992 after being called up as last-minute replacements', 'Christian Eriksen collapsed on pitch at Euro 2020 — returned to play'],
    players: [],
  },
  {
    id: 'AUS', name: 'Australia', flag: '🇦🇺', rating: 71, rank: 20, group: 'D',
    coach: 'Graham Arnold', mascot: 'Socceroo Skippy', style: 'Hard-working defensive structure with aerial threat',
    titles: 0, finals: 0, semifinals: 0, bestResult: 'Round of 16 (2022)',
    facts: ['Beat Denmark to reach the 2022 WC knockout rounds for the second time', 'Changed confederation from OFC to AFC in 2006'],
    players: [],
  },
  {
    id: 'KOR', name: 'South Korea', flag: '🇰🇷', rating: 74, rank: 21, group: 'E',
    coach: 'Hong Myung-bo', mascot: 'Red Devil Tiger', style: 'Relentless pressing with explosive pace on the break',
    titles: 0, finals: 0, semifinals: 1, bestResult: 'Fourth place (2002)',
    facts: ['Reached the 2002 WC semifinals as co-hosts — beat Spain and Italy', 'Son Heung-min is Asia\'s greatest-ever footballer'],
    players: [],
  },
  {
    id: 'CAN', name: 'Canada', flag: '🇨🇦', rating: 72, rank: 22, group: 'H',
    coach: 'Jesse Marsch', mascot: 'Maple Voyageur', style: 'High-energy pressing with emerging young talent',
    titles: 0, finals: 0, semifinals: 0, bestResult: 'Group stage (1986, 2022)',
    facts: ['Only played in two World Cups before 2026', 'Co-hosting 2026 — first WC matches on Canadian soil since 1986'],
    players: [],
  },
  {
    id: 'NGA', name: 'Nigeria', flag: '🇳🇬', rating: 73, rank: 23, group: 'F',
    coach: 'Finidi George', mascot: 'Super Eagle', style: 'Pace and power with flair in the final third',
    titles: 0, finals: 0, semifinals: 0, bestResult: 'Round of 16 (1994, 1998, 2014)',
    facts: ['Won the 1996 Olympic gold medal in football — beat Argentina in the final', 'The Super Eagles have the most iconic kits in WC history'],
    players: [],
  },
  {
    id: 'ECU', name: 'Ecuador', flag: '🇪🇨', rating: 73, rank: 24, group: 'H',
    coach: 'Félix Sánchez', mascot: 'El Cóndor Andino', style: 'Altitude-hardened fitness with direct attacking play',
    titles: 0, finals: 0, semifinals: 0, bestResult: 'Round of 16 (2006)',
    facts: ['Home matches in Quito at 2,850m altitude give a massive advantage', 'Énner Valencia scored in every WC match he played'],
    players: [],
  },
  {
    id: 'POL', name: 'Poland', flag: '🇵🇱', rating: 74, rank: 25, group: 'H',
    coach: 'Michał Probierz', mascot: 'White Eagle', style: 'Defensive solidity with Lewandowski as the focal point',
    titles: 0, finals: 0, semifinals: 2, bestResult: 'Third place (1974, 1982)',
    facts: ['Robert Lewandowski is the greatest Polish footballer of all time', 'Finished third in two World Cups but haven\'t won a knockout game since 1982'],
    players: [],
  },
  {
    id: 'SRB', name: 'Serbia', flag: '🇷🇸', rating: 73, rank: 26, group: 'F',
    coach: 'Dragan Stojković', mascot: 'White Eagle', style: 'Technical midfield play with strong physical presence',
    titles: 0, finals: 0, semifinals: 1, bestResult: 'Fourth place (1930, 1962 as Yugoslavia)',
    facts: ['Produced some of Europe\'s finest midfielders across generations', 'First WC as independent Serbia was in 2010'],
    players: [],
  },
  {
    id: 'IRN', name: 'Iran', flag: '🇮🇷', rating: 68, rank: 27, group: 'G',
    coach: 'Amir Ghalenoei', mascot: 'Persian Cheetah', style: 'Organized low block with dangerous set-piece routines',
    titles: 0, finals: 0, semifinals: 0, bestResult: 'Group stage (1978, 1998, 2006, 2014, 2018, 2022)',
    facts: ['Asia\'s most successful WC qualifying nation', 'Beat the USA 2-1 in the 1998 World Cup'],
    players: [],
  },
  {
    id: 'GHA', name: 'Ghana', flag: '🇬🇭', rating: 67, rank: 28, group: 'D',
    coach: 'Otto Addo', mascot: 'Black Star', style: 'Energetic pressing with raw pace and physicality',
    titles: 0, finals: 0, semifinals: 0, bestResult: 'Quarterfinals (2010)',
    facts: ['Suárez\'s handball on the line in the 2010 QF is WC\'s most controversial moment', 'Asamoah Gyan missed the resulting penalty — heartbreak for Africa'],
    players: [],
  },
  {
    id: 'CMR', name: 'Cameroon', flag: '🇨🇲', rating: 68, rank: 29, group: 'A',
    coach: 'Rigobert Song', mascot: 'Indomitable Lion', style: 'Athletic and aggressive with never-say-die mentality',
    titles: 0, finals: 0, semifinals: 0, bestResult: 'Quarterfinals (1990)',
    facts: ['Roger Milla became the oldest WC scorer at 42 years old in 1994', 'Beat Argentina in the 1990 opener — the original giant-killing'],
    players: [],
  },
  {
    id: 'TUN', name: 'Tunisia', flag: '🇹🇳', rating: 66, rank: 30, group: 'E',
    coach: 'Jalel Kadri', mascot: 'Carthage Eagle', style: 'Compact defensive structure with tactical discipline',
    titles: 0, finals: 0, semifinals: 0, bestResult: 'Group stage (1978, 1998, 2002, 2006, 2018, 2022)',
    facts: ['Beat France in the 2022 WC group stage — first African win over Les Bleus', 'Six WC appearances but never reached the knockout rounds'],
    players: [],
  },
  {
    id: 'KSA', name: 'Saudi Arabia', flag: '🇸🇦', rating: 64, rank: 31, group: 'B',
    coach: 'Roberto Mancini', mascot: 'Green Falcon', style: 'Disciplined defensive block with rapid transitions',
    titles: 0, finals: 0, semifinals: 0, bestResult: 'Round of 16 (1994)',
    facts: ['Beat Argentina 2-1 in the 2022 WC opener — biggest upset in decades', 'The Saudi league became the world\'s most talked-about in 2023'],
    players: [],
  },
  {
    id: 'CRC', name: 'Costa Rica', flag: '🇨🇷', rating: 63, rank: 32, group: 'C',
    coach: 'Claudio Vivas', mascot: 'Tico Toucan', style: 'Deep defensive block with resilient counter-attacking',
    titles: 0, finals: 0, semifinals: 0, bestResult: 'Quarterfinals (2014)',
    facts: ['Beat Uruguay, Italy and England\'s group in 2014 — the ultimate Cinderella', 'Keylor Navas became a Real Madrid legend after that World Cup run'],
    players: [],
  },
];

export const PLAYERS: Player[] = [
  {
    id: 'vinicius', name: 'Vinicius Jr', flag: '🇧🇷', team: 'Brazil', teamId: 'BRA', pos: 'LW', ovr: 92,
    attrs: { PAC: 97, SHO: 87, PAS: 82, DRI: 95, DEF: 28, PHY: 74 },
    form: ['W', 'W', 'W', 'D', 'W'],
    wcStats: { goals: 4, assists: 3, rating: 9.1, matches: 5, xG: 3.8, passAccuracy: 86 },
    heatmap: { ATK: 92, MID: 45, DEF: 12, WID: 88 },
    bio: 'Real Madrid superstar and the tournament\'s most electric presence. Unstoppable on the left wing.',
  },
  {
    id: 'mbappe', name: 'Kylian Mbappé', flag: '🇫🇷', team: 'France', teamId: 'FRA', pos: 'ST', ovr: 91,
    attrs: { PAC: 98, SHO: 90, PAS: 80, DRI: 93, DEF: 36, PHY: 78 },
    form: ['W', 'D', 'W', 'W', 'W'],
    wcStats: { goals: 5, assists: 2, rating: 8.9, matches: 5, xG: 4.2, passAccuracy: 82 },
    heatmap: { ATK: 95, MID: 55, DEF: 8, WID: 72 },
    bio: 'Already the WC\'s top scorer at age 26. Leads France with the cold efficiency of a player who has been here before.',
  },
  {
    id: 'yamal', name: 'Lamine Yamal', flag: '🇪🇸', team: 'Spain', teamId: 'ESP', pos: 'RW', ovr: 88,
    attrs: { PAC: 90, SHO: 82, PAS: 86, DRI: 94, DEF: 30, PHY: 62 },
    form: ['W', 'W', 'W', 'W', 'D'],
    wcStats: { goals: 3, assists: 4, rating: 8.8, matches: 5, xG: 2.9, passAccuracy: 89 },
    heatmap: { ATK: 85, MID: 50, DEF: 10, WID: 95 },
    bio: 'At 18, the youngest player ever to appear in a World Cup for Spain. His combination play with Pedri is generational.',
  },
  {
    id: 'bellingham', name: 'Jude Bellingham', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', team: 'England', teamId: 'ENG', pos: 'CAM', ovr: 89,
    attrs: { PAC: 82, SHO: 85, PAS: 87, DRI: 88, DEF: 70, PHY: 84 },
    form: ['W', 'W', 'D', 'W', 'W'],
    wcStats: { goals: 3, assists: 3, rating: 8.7, matches: 5, xG: 2.4, passAccuracy: 91 },
    heatmap: { ATK: 75, MID: 92, DEF: 48, WID: 40 },
    bio: 'The complete modern midfielder. Covers every blade of grass, scores in big moments, carries England without complaint.',
  },
  {
    id: 'messi', name: 'Lionel Messi', flag: '🇦🇷', team: 'Argentina', teamId: 'ARG', pos: 'CF', ovr: 90,
    attrs: { PAC: 72, SHO: 91, PAS: 94, DRI: 96, DEF: 32, PHY: 60 },
    form: ['W', 'W', 'W', 'D', 'W'],
    wcStats: { goals: 4, assists: 6, rating: 9.3, matches: 5, xG: 3.5, passAccuracy: 93 },
    heatmap: { ATK: 88, MID: 70, DEF: 15, WID: 55 },
    bio: 'Last dance. Fifth World Cup. Still the best. At 38, his football brain and vision are at their absolute peak.',
  },
];

export const STADIUMS: Record<string, Stadium> = {
  'MetLife Stadium': {
    name: 'MetLife Stadium', city: 'East Rutherford', country: 'USA', capacity: 82500,
    surface: 'Natural grass', opened: 2010, cost: '$1.6 billion',
    host: 'Final + 8 other matches',
    facts: [
      'Largest stadium in the WC tournament — 82,500 seats',
      'Home of NY Giants and NY Jets',
      'Open air — weather can be extreme in July',
      'Built specifically to host major events',
    ],
    coordinates: { lat: 40.8135, lng: -74.0745 },
  },
  'AT&T Stadium': {
    name: 'AT&T Stadium', city: 'Arlington', country: 'USA', capacity: 80000,
    surface: 'Retractable artificial turf', opened: 2009, cost: '$1.3 billion',
    host: '8 matches including a semifinal',
    facts: [
      'Climate-controlled dome — no weather issues for players or fans',
      'The roof opens in just 18 minutes',
      'Has the world\'s largest HD video screen (160m wide)',
      'Known as "Jerry World" after owner Jerry Jones',
    ],
    coordinates: { lat: 32.7473, lng: -97.0945 },
  },
  'SoFi Stadium': {
    name: 'SoFi Stadium', city: 'Inglewood', country: 'USA', capacity: 70240,
    surface: 'Artificial turf', opened: 2020, cost: '$5.5 billion (most expensive ever)',
    host: '8 matches',
    facts: [
      'Most expensive stadium ever constructed',
      '70,000 sq ft HD screen wrapping the seating bowl',
      'Fully enclosed but not climate controlled',
      'Home of LA Rams and LA Chargers',
    ],
    coordinates: { lat: 33.9535, lng: -118.3392 },
  },
  'Estadio Azteca': {
    name: 'Estadio Azteca', city: 'Mexico City', country: 'Mexico', capacity: 87523,
    surface: 'Natural grass', opened: 1966, cost: 'Renovated for $100M in 2023',
    host: '3 group stage matches',
    facts: [
      'Highest altitude WC venue at 2,240m — affects stamina significantly',
      'Only stadium to host 2 WC finals (1970 and 1986)',
      'Maradona\'s "Hand of God" goal was scored here in 1986',
      'Original capacity was 105,000 — reduced after 1985 earthquake',
    ],
    coordinates: { lat: 19.3029, lng: -99.1505 },
  },
};

export const MOCK_GROUPS: Group[] = [
  {
    id: 'A', name: 'Group A',
    teams: [TEAMS[0], TEAMS[5], { ...TEAMS[0], id: 'JPN', name: 'Japan', flag: '🇯🇵', rating: 73, rank: 12 } as Team, { ...TEAMS[0], id: 'CAM', name: 'Cameroon', flag: '🇨🇲', rating: 62, rank: 28 } as Team],
    standings: [],
    matches: [],
  },
];

export const FAN_IQ_LEVELS = [
  { level: 'Casual Fan', min: 0, max: 20 },
  { level: 'Football Nerd', min: 21, max: 40 },
  { level: 'Tactical Analyst', min: 41, max: 60 },
  { level: 'Scout', min: 61, max: 80 },
  { level: 'World Cup Oracle', min: 81, max: 100 },
];
