interface TournamentHistoryPlayer { name: string; flag: string; team: string; goals: number; assists: number; rating: number; }
interface TournamentHistoryTeam { id: string; name: string; flag: string; avgRating: number; goalsScored: number; goalsConceded: number; bigChances: number; }
interface TournamentHistoryEntry { year: number; host: string; hostFlag: string; winner: { name: string; flag: string; id: string }; runnerUp: { name: string; flag: string; id: string }; finalScore: string; topPlayers: TournamentHistoryPlayer[]; topTeams: TournamentHistoryTeam[]; }

export const TOURNAMENT_HISTORY: TournamentHistoryEntry[] = [
  {
    year: 2022, host: 'Qatar', hostFlag: '🇶🇦',
    winner: { name: 'Argentina', flag: '🇦🇷', id: 'ARG' },
    runnerUp: { name: 'France', flag: '🇫🇷', id: 'FRA' },
    finalScore: '3-3 (4-2 pens)',
    topPlayers: [
      { name: 'Kylian Mbappé', flag: '🇫🇷', team: 'France', goals: 4, assists: 2, rating: 8.7 },
      { name: 'Lionel Messi', flag: '🇦🇷', team: 'Argentina', goals: 7, assists: 3, rating: 9.1 },
      { name: 'Olivier Giroud', flag: '🇫🇷', team: 'France', goals: 4, assists: 0, rating: 7.4 },
      { name: 'Julián Álvarez', flag: '🇦🇷', team: 'Argentina', goals: 4, assists: 1, rating: 7.9 },
      { name: 'Gonçalo Ramos', flag: '🇵🇹', team: 'Portugal', goals: 3, assists: 1, rating: 7.6 },
    ],
    topTeams: [
      { id: 'ARG', name: 'Argentina', flag: '🇦🇷', avgRating: 88, goalsScored: 15, goalsConceded: 8, bigChances: 22 },
      { id: 'FRA', name: 'France', flag: '🇫🇷', avgRating: 86, goalsScored: 16, goalsConceded: 8, bigChances: 20 },
      { id: 'CRO', name: 'Croatia', flag: '🇭🇷', avgRating: 84, goalsScored: 8, goalsConceded: 7, bigChances: 12 },
      { id: 'MAR', name: 'Morocco', flag: '🇲🇦', avgRating: 82, goalsScored: 6, goalsConceded: 2, bigChances: 10 },
      { id: 'BRA', name: 'Brazil', flag: '🇧🇷', avgRating: 86, goalsScored: 8, goalsConceded: 3, bigChances: 18 },
      { id: 'ENG', name: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', avgRating: 83, goalsScored: 13, goalsConceded: 4, bigChances: 16 },
      { id: 'NED', name: 'Netherlands', flag: '🇳🇱', avgRating: 82, goalsScored: 10, goalsConceded: 5, bigChances: 14 },
      { id: 'POR', name: 'Portugal', flag: '🇵🇹', avgRating: 83, goalsScored: 12, goalsConceded: 6, bigChances: 15 },
    ],
  },
  {
    year: 2018, host: 'Russia', hostFlag: '🇷🇺',
    winner: { name: 'France', flag: '🇫🇷', id: 'FRA' },
    runnerUp: { name: 'Croatia', flag: '🇭🇷', id: 'CRO' },
    finalScore: '4-2',
    topPlayers: [
      { name: 'Harry Kane', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', team: 'England', goals: 6, assists: 0, rating: 7.8 },
      { name: 'Kylian Mbappé', flag: '🇫🇷', team: 'France', goals: 4, assists: 1, rating: 8.4 },
      { name: 'Antoine Griezmann', flag: '🇫🇷', team: 'France', goals: 4, assists: 2, rating: 8.2 },
      { name: 'Romelu Lukaku', flag: '🇧🇪', team: 'Belgium', goals: 4, assists: 1, rating: 7.5 },
      { name: 'Denis Cheryshev', flag: '🇷🇺', team: 'Russia', goals: 4, assists: 0, rating: 7.3 },
    ],
    topTeams: [
      { id: 'FRA', name: 'France', flag: '🇫🇷', avgRating: 87, goalsScored: 14, goalsConceded: 6, bigChances: 19 },
      { id: 'CRO', name: 'Croatia', flag: '🇭🇷', avgRating: 83, goalsScored: 14, goalsConceded: 9, bigChances: 15 },
      { id: 'BEL', name: 'Belgium', flag: '🇧🇪', avgRating: 86, goalsScored: 16, goalsConceded: 6, bigChances: 21 },
      { id: 'ENG', name: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', avgRating: 82, goalsScored: 12, goalsConceded: 8, bigChances: 14 },
      { id: 'BRA', name: 'Brazil', flag: '🇧🇷', avgRating: 85, goalsScored: 8, goalsConceded: 3, bigChances: 16 },
      { id: 'URU', name: 'Uruguay', flag: '🇺🇾', avgRating: 80, goalsScored: 7, goalsConceded: 3, bigChances: 10 },
    ],
  },
  {
    year: 2014, host: 'Brazil', hostFlag: '🇧🇷',
    winner: { name: 'Germany', flag: '🇩🇪', id: 'GER' },
    runnerUp: { name: 'Argentina', flag: '🇦🇷', id: 'ARG' },
    finalScore: '1-0 (AET)',
    topPlayers: [
      { name: 'James Rodríguez', flag: '🇨🇴', team: 'Colombia', goals: 6, assists: 2, rating: 8.6 },
      { name: 'Thomas Müller', flag: '🇩🇪', team: 'Germany', goals: 5, assists: 3, rating: 8.1 },
      { name: 'Neymar', flag: '🇧🇷', team: 'Brazil', goals: 4, assists: 1, rating: 8.0 },
      { name: 'Lionel Messi', flag: '🇦🇷', team: 'Argentina', goals: 4, assists: 1, rating: 8.5 },
      { name: 'Robin van Persie', flag: '🇳🇱', team: 'Netherlands', goals: 3, assists: 1, rating: 7.7 },
    ],
    topTeams: [
      { id: 'GER', name: 'Germany', flag: '🇩🇪', avgRating: 88, goalsScored: 18, goalsConceded: 4, bigChances: 24 },
      { id: 'ARG', name: 'Argentina', flag: '🇦🇷', avgRating: 85, goalsScored: 8, goalsConceded: 4, bigChances: 12 },
      { id: 'NED', name: 'Netherlands', flag: '🇳🇱', avgRating: 84, goalsScored: 15, goalsConceded: 4, bigChances: 18 },
      { id: 'BRA', name: 'Brazil', flag: '🇧🇷', avgRating: 83, goalsScored: 11, goalsConceded: 14, bigChances: 16 },
      { id: 'COL', name: 'Colombia', flag: '🇨🇴', avgRating: 82, goalsScored: 12, goalsConceded: 4, bigChances: 14 },
      { id: 'FRA', name: 'France', flag: '🇫🇷', avgRating: 81, goalsScored: 10, goalsConceded: 3, bigChances: 13 },
    ],
  },
  {
    year: 2010, host: 'South Africa', hostFlag: '🇿🇦',
    winner: { name: 'Spain', flag: '🇪🇸', id: 'ESP' },
    runnerUp: { name: 'Netherlands', flag: '🇳🇱', id: 'NED' },
    finalScore: '1-0 (AET)',
    topPlayers: [
      { name: 'Thomas Müller', flag: '🇩🇪', team: 'Germany', goals: 5, assists: 3, rating: 8.0 },
      { name: 'David Villa', flag: '🇪🇸', team: 'Spain', goals: 5, assists: 1, rating: 8.2 },
      { name: 'Wesley Sneijder', flag: '🇳🇱', team: 'Netherlands', goals: 5, assists: 1, rating: 8.4 },
      { name: 'Diego Forlán', flag: '🇺🇾', team: 'Uruguay', goals: 5, assists: 0, rating: 8.6 },
      { name: 'Asamoah Gyan', flag: '🇬🇭', team: 'Ghana', goals: 3, assists: 1, rating: 7.5 },
    ],
    topTeams: [
      { id: 'ESP', name: 'Spain', flag: '🇪🇸', avgRating: 89, goalsScored: 8, goalsConceded: 2, bigChances: 15 },
      { id: 'NED', name: 'Netherlands', flag: '🇳🇱', avgRating: 85, goalsScored: 12, goalsConceded: 6, bigChances: 16 },
      { id: 'GER', name: 'Germany', flag: '🇩🇪', avgRating: 86, goalsScored: 16, goalsConceded: 5, bigChances: 22 },
      { id: 'URU', name: 'Uruguay', flag: '🇺🇾', avgRating: 82, goalsScored: 11, goalsConceded: 5, bigChances: 13 },
      { id: 'BRA', name: 'Brazil', flag: '🇧🇷', avgRating: 84, goalsScored: 9, goalsConceded: 4, bigChances: 14 },
      { id: 'ARG', name: 'Argentina', flag: '🇦🇷', avgRating: 83, goalsScored: 10, goalsConceded: 6, bigChances: 12 },
    ],
  },
  {
    year: 2006, host: 'Germany', hostFlag: '🇩🇪',
    winner: { name: 'Italy', flag: '🇮🇹', id: 'ITA' },
    runnerUp: { name: 'France', flag: '🇫🇷', id: 'FRA' },
    finalScore: '1-1 (5-3 pens)',
    topPlayers: [
      { name: 'Miroslav Klose', flag: '🇩🇪', team: 'Germany', goals: 5, assists: 0, rating: 7.9 },
      { name: 'Hernán Crespo', flag: '🇦🇷', team: 'Argentina', goals: 3, assists: 1, rating: 7.5 },
      { name: 'Zinedine Zidane', flag: '🇫🇷', team: 'France', goals: 3, assists: 2, rating: 8.8 },
      { name: 'Thierry Henry', flag: '🇫🇷', team: 'France', goals: 3, assists: 1, rating: 7.8 },
      { name: 'Maxi Rodríguez', flag: '🇦🇷', team: 'Argentina', goals: 2, assists: 2, rating: 7.6 },
    ],
    topTeams: [
      { id: 'ITA', name: 'Italy', flag: '🇮🇹', avgRating: 86, goalsScored: 12, goalsConceded: 2, bigChances: 14 },
      { id: 'FRA', name: 'France', flag: '🇫🇷', avgRating: 85, goalsScored: 9, goalsConceded: 3, bigChances: 13 },
      { id: 'GER', name: 'Germany', flag: '🇩🇪', avgRating: 84, goalsScored: 14, goalsConceded: 6, bigChances: 18 },
      { id: 'ARG', name: 'Argentina', flag: '🇦🇷', avgRating: 84, goalsScored: 11, goalsConceded: 3, bigChances: 15 },
      { id: 'BRA', name: 'Brazil', flag: '🇧🇷', avgRating: 85, goalsScored: 10, goalsConceded: 3, bigChances: 16 },
      { id: 'POR', name: 'Portugal', flag: '🇵🇹', avgRating: 82, goalsScored: 7, goalsConceded: 5, bigChances: 10 },
    ],
  },
  {
    year: 2002, host: 'South Korea / Japan', hostFlag: '🇰🇷🇯🇵',
    winner: { name: 'Brazil', flag: '🇧🇷', id: 'BRA' },
    runnerUp: { name: 'Germany', flag: '🇩🇪', id: 'GER' },
    finalScore: '2-0',
    topPlayers: [
      { name: 'Ronaldo', flag: '🇧🇷', team: 'Brazil', goals: 8, assists: 0, rating: 8.9 },
      { name: 'Miroslav Klose', flag: '🇩🇪', team: 'Germany', goals: 5, assists: 1, rating: 7.8 },
      { name: 'Rivaldo', flag: '🇧🇷', team: 'Brazil', goals: 5, assists: 2, rating: 8.4 },
      { name: 'Vieri', flag: '🇮🇹', team: 'Italy', goals: 4, assists: 0, rating: 7.8 },
      { name: 'Ballack', flag: '🇩🇪', team: 'Germany', goals: 3, assists: 2, rating: 8.0 },
    ],
    topTeams: [
      { id: 'BRA', name: 'Brazil', flag: '🇧🇷', avgRating: 90, goalsScored: 18, goalsConceded: 4, bigChances: 25 },
      { id: 'GER', name: 'Germany', flag: '🇩🇪', avgRating: 83, goalsScored: 14, goalsConceded: 3, bigChances: 16 },
      { id: 'KOR', name: 'South Korea', flag: '🇰🇷', avgRating: 76, goalsScored: 8, goalsConceded: 6, bigChances: 10 },
      { id: 'ESP', name: 'Spain', flag: '🇪🇸', avgRating: 82, goalsScored: 10, goalsConceded: 5, bigChances: 13 },
      { id: 'ENG', name: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', avgRating: 81, goalsScored: 6, goalsConceded: 3, bigChances: 11 },
      { id: 'SEN', name: 'Senegal', flag: '🇸🇳', avgRating: 75, goalsScored: 7, goalsConceded: 4, bigChances: 9 },
    ],
  },
];
